docs: Add Prisma documentation
TypedProject/ts-express-decorators pull request #1404
Opened 2021-05-21 08:42 UTC by Romakita

## Information

Type | Breaking change
---|---
Feature/Fix/Doc/Chore | Yes/No

****

## Todos

- [ ] Tests
- [ ] Coverage
- [ ] Example
- [ ] Documentation

2021-05-22 09:01 UTC, LorianeE requested changes

2021-05-22 09:01 UTC, LorianeE commented on docs/tutorials/prisma-client.md
> +Now the Ts.ED generator is correctly configured you can go back (or follow) the tutorial to create the [PrismaService](/tutorials/prisma.md#)
```suggestion
Now that the Ts.ED generator is correctly configured, you can go back (or follow) the tutorial to create the [PrismaService](/tutorials/prisma.md#)
```

2021-05-22 13:39 UTC, LorianeE requested changes

2021-05-22 13:39 UTC, LorianeE commented on docs/tutorials/prisma.md
> +If you are premium sponsors, or you want to become it, you can ask [Ts.ED team](https://api.tsed.io/rest/slack/tsedio/tsed) to get your access to the private packages [`@tsedio/prisma`](/tutorials/pr
```suggestion
If you are a premium sponsor, or you want to become one, you can ask [Ts.ED team](https://api.tsed.io/rest/slack/tsedio/tsed) to get your access to the private packages [`@tsedio/prisma`](/tutorials/prisma-client.md). 
```

2021-05-22 13:39 UTC, LorianeE commented on docs/tutorials/prisma.md
> +This package generates enums and classes compatible with the Ts.ED decorators like @@Returns@@ and extend the possibility about the `prisma.schema`.
```suggestion
This package generates enums and classes compatible with the Ts.ED decorators like @@Returns@@ and extends possibilities about the `prisma.schema`.
```

2021-05-22 13:39 UTC, LorianeE commented on docs/tutorials/prisma.md
> +The following tutorial is to be followed to create your project. You will have more details regarding the installation of the [`@tsedio/prisma`](/tutorials/prisma-client.md) package.
```suggestion
You should follow this tutorial to create your project properly. You will have more details regarding the installation of the [`@tsedio/prisma`](/tutorials/prisma-client.md) package.
```

2021-05-22 13:39 UTC, LorianeE commented on docs/tutorials/prisma.md
> +npm install --save-dev prima
t'es sûr que c'est "prima" et pas "prisma" ?

2021-05-22 13:39 UTC, LorianeE commented on docs/tutorials/prisma.md
> +In the following steps, we'll be utilizing the [Prisma CLI](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-cli).
we'll be using ?

2021-05-22 13:39 UTC, LorianeE commented on docs/tutorials/prisma.md
> +In this case, the following migration files was created in the existing `prisma` directory:
```suggestion
In this case, the following migration file was created in the existing `prisma` directory:
```

2021-05-22 13:39 UTC, LorianeE commented on docs/tutorials/prisma.md
> +The generated interfaces cannot be used with `@Returns` to describe the Swagger documentation! You have to use the premium packages [`@tsedio/prisma`](/tutorials/prisma-client.md)
```suggestion
The generated interfaces cannot be used with `@Returns` to describe the Swagger documentation! You have to use the premium package [`@tsedio/prisma`](/tutorials/prisma-client.md)
```

2021-05-22 13:39 UTC, LorianeE commented on docs/tutorials/prisma.md
> +Now our `prisma.schema` is ready for the basic usage. It's time to configure the [`@tsedio/prisma`](/tutorials/prisma-client.md)
```suggestion
Now our `prisma.schema` is ready for the basic usage. It's time to configure [`@tsedio/prisma`](/tutorials/prisma-client.md)
```

2021-05-22 13:39 UTC, LorianeE commented on docs/tutorials/prisma.md
> +Now we have to create controllers to exposes your business to our consumers. So create the following controllers in `src/controllers` directory:
```suggestion
Now we have to create controllers to expose your business to our consumers. So create the following controllers in `src/controllers` directory:
```

2021-05-22 13:39 UTC, LorianeE commented on docs/tutorials/prisma.md
> +The controller that implements the routes of the API is calling a `PrismaService` which in turn uses Prisma Client to send queries to a database to fulfill the data needs of incoming requests.
```suggestion
The controller implementing the routes of the API is calling a `PrismaService` which in turn uses Prisma Client to send queries to a database to fulfill the data needed by incoming requests.
```
le "needed by" je suis pas sûre que c'était ce que tu voulais dire, mais la phrase d'origine n'a pas de sens :P

2021-05-22 14:28 UTC, Romakita commented on docs/tutorials/prisma-client.md
> +Ask Ts.ED team on slack to get an uniq personal GH_TOKEN.
j'ai réparé le lien via l'api Ts.ED https://api.tsed.io/rest/slack/tsedio/tsed

2021-05-22 14:29 UTC, Romakita commented on docs/tutorials/prisma-client.md
> +By default, when the output path contains `node_modules`, the generated code is transpiled - consist of `*.js` and `*.d.ts` files that are ready to use (import) in your code.
je suis pas l'auteur de cette ligne XD

2021-05-22 14:29 UTC, Romakita commented on docs/tutorials/prisma.md
> +In the following steps, we'll be utilizing the [Prisma CLI](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-cli).
Ok :)

2021-05-22 14:30 UTC, Romakita commented on docs/tutorials/prisma.md
> +The controller that implements the routes of the API is calling a `PrismaService` which in turn uses Prisma Client to send queries to a database to fulfill the data needs of incoming requests.
C'est copié d'un autre tuto...

2021-05-23 13:26 UTC, Romakita commented on docs/tutorials/prisma.md
> +npm install --save-dev prima
prisma

2021-05-23 13:52 UTC, Romakita commented
@LorianeE  C'est fait.  J'ai repousé un dernier commit avec des ajustements de contenu ;)

2021-05-24 06:49 UTC, merged