OIDC
TypedProject/ts-express-decorators pull request #1490
Opened 2021-08-16 12:28 UTC by stefanvanherwijnen

A few points:
- Because oidc-provider is a koa app with a catch-all route, mounting it at `/` intervenes with the TSed exception handler. This is fixed by mounting it at `/oidc` and rewriting the route for the discovery documentation.
- For Koa, oidc needs to be mounted differently which now works correctly (previously all requests would be handled by both the TSed and oidc-provider koa instance)
- There are no type declarations for koa-rewrite, which results in `test/app` not compiling. I couldn't figure out how to fix this.
- I cleaned the documentation and embedded the files from the `test/app` directory.
- I added documentation for a TLS proxy using Caddy.

I couldn't directly test the app/documentation as it does not compile, so if you know a fix that would be great. Because the code is now embedded in the docs, if the test app works the documentation is also correct.

The CLI plugin is almost finished, but I want to make sure everything is consistent along all documentation.
For example, the CLI initializes an app with default port 8083, and the documentation used 8081. I'd like to make sure that the CLI automates the steps in the documentation without modifications.

2021-08-16 12:53 UTC, Romakita commented
Hello @stefanvanherwijnen
Thanks for the PR

2021-08-16 12:56 UTC, Romakita commented
Hello @stefanvanherwijnen 

Thanks for the PR.

> There are no type declarations for koa-rewrite, which results in test/app not compiling. I couldn't figure out how to fix this.   
The test app in packages/oidc ? Can you give me more details?

> Because the code is now embedded in the docs
I don't understand this point...

> The CLI plugin is almost finished, but I want to make sure everything is consistent along all documentation.
> For example, the CLI initializes an app with default port 8083, and the documentation used 8081. I'd like to make sure that the CLI automates the steps in the documentation without modifications.

Update documentation is possible to be aligned with the CLI ;)

2021-08-16 13:26 UTC, stefanvanherwijnen commented
> Hello @stefanvanherwijnen
> 
> Thanks for the PR.
> 
> > There are no type declarations for koa-rewrite, which results in test/app not compiling. I couldn't figure out how to fix this.
> 
> The test app in packages/oidc ? Can you give me more details?
> 

Yes. Running `yarn start` results in "src/OidcModule.ts:7:21 - error TS7016: Could not find a declaration file for module 'koa-rewrite'". In `src` I manually declared `koa-rewrite`, but it doesn't seem to get picked up when using `yarn start`. Ideally `yarn start` would spin up a working application on which the URLs defined in the documentation can be opened (e.g. the .well-known route).

> > Because the code is now embedded in the docs
> 
> I don't understand this point...

I mean using "<<< @/../packages/oidc-provider/src/domain/OidcSettings.ts" instead of copy-pasting the code into the documentation. This way it is easier to keep everything in sync without having to check everything manually.


I am working on fixing the integration test.

2021-08-16 14:25 UTC, stefanvanherwijnen commented
The coverage test seems to fail but I am not sure how to fix it.

2021-08-16 17:36 UTC, Romakita commented
> Yes. Running yarn start results in "src/OidcModule.ts:7:21 - error TS7016: Could not find a declaration file for module 'koa-rewrite'". In src I manually declared koa-rewrite, but it doesn't seem to get picked up when using yarn start. Ideally yarn start would spin up a working application on which the URLs defined in the documentation can be opened (e.g. the .well-known route).

You can simply use require instead of import from for this case ;)

> I mean using "<<< @/../packages/oidc-provider/src/domain/OidcSettings.ts" instead of copy-pasting the code into the documentation. This way it is easier to keep everything in sync without having to check everything manually.

Ok I see ;) I'm ok to use this way !!

2021-08-16 19:57 UTC, stefanvanherwijnen commented
Thanks, one more thing which does not seem to work: the `Post()` routes in the interactions do not seem to get registered when using koa. E.g. POST to `/interactions/123/login` results in a NOT_FOUND error with koa, but with express it results in SessionNotFound as expected. The main GET routes do work fine.

Any clue?

2021-08-17 06:48 UTC, Romakita requested changes

2021-08-17 06:48 UTC, Romakita commented on packages/oidc-provider/src/OidcModule.ts
> +        this.app.use(mount("/oidc", provider.app));
hum... let the user to configure the correct path from configuration could be a better options. Because today, /oidc isn't the default path and it will be a breaking change. no?

2021-08-17 06:48 UTC, Romakita commented on packages/oidc-provider/src/OidcModule.ts
> +
```typescript
@Constant('oidc.path', '/')
private basePath: string;
```

2021-08-17 06:48 UTC, Romakita commented on packages/oidc-provider/src/OidcModule.ts
> +    if (this.platformName === "koa") {
```typescript
const urlRewrite = [this.basePath, ".well-known/$1"].join('/')

 if (this.platformName === "koa") {
    this.app.use(rewrite("/.well-known/(.*)", urlRewrite);
  } else {
    this.app.use(expressRewrite("/.well-known/*", urlRewrite));
  }
```

2021-08-17 06:48 UTC, Romakita commented on packages/oidc-provider/src/OidcModule.ts
> +        this.app.use(mount("/oidc", provider.app));
```typescript
      if (this.platformName === "koa") {
        this.app.use(mount(this.basePath, provider.app));
      } else {
        this.app.use(this.basePath, provider.callback());
      }
```

2021-08-17 06:48 UTC, Romakita commented on packages/oidc-provider/src/OidcModule.ts
> +
Or maybe we can try to retrieve the path of the InteractionsCtrl ?

2021-08-17 06:48 UTC, Romakita commented on packages/oidc-provider/src/OidcModule.ts
> +        this.app.use(mount("/oidc", provider.app));
```typescript
  $onReady() {
    if (this.oidcProvider.hasConfiguration()) {
      const {injector} = this;
      const {httpsPort, httpPort} = injector.settings;

      const displayLog = (host: any) => {
        const url = [`${host.protocol}://${host.address}`, typeof host.port === "number" && host.port].filter(Boolean).join(":") + (this.basePath === "/" ? "" : this.basePath);

        injector.logger.info(`WellKnown is available on ${url}/.well-known/openid-configuration`);
      };
```

2021-08-17 06:48 UTC, Romakita commented on packages/oidc-provider/src/OidcModule.ts
> +
```typescript
private getBasePath() {
  const provider = this.injector.getProviders().find((provider) => provider.subType === INTERACTIONS);
  if (provider) {
     return provider.path.split('/interaction')[0] || "/"
  }  
  return "/"
}

$onRoutesInit() {
   this.basePath = this.getBasePath()
  //....
}
```

With this code, the basePath will always aligned with the InteractionsCtrl path :)

2021-08-17 06:48 UTC, Romakita commented on packages/oidc-provider/src/OidcModule.ts
> +    if (this.platformName === "koa") {
I'm not sure is this code is necessary. The OIDC client will consume the configured issuer url. So
if the server expose oidc under a subpath, the client should be configured with the correct url:

```
const { Issuer } = require('openid-client');
Issuer.discover('https://accounts.myserver.com/oidc') // => Promise
  .then(function (issuer) {
      
  });
```

For me the url rewrite isn't necessary because the .well-known will be available under "/oidc" if the InteractionsCtrl have a "/oidc" subpath.

2021-08-17 06:48 UTC, Romakita commented on packages/oidc-provider/test/oidc.integration.spec.ts
> +      .get("/oidc/auth?client_id=client_id&response_type=id_token&scope=openid+email&nonce=foobar&prompt=login&redirect_uri=http://localhost:3000")
The unit shown that the changes are a breaking change :). I prefer to let the "/" subpath by default and let the developer to configure the InteractionsCtrl with the custom subpath !

2021-08-17 06:49 UTC, Romakita commented
For the corevage, we will see that later. But we can add the unit test on the OIDCModule to cover correctly the code :)

2021-08-17 08:16 UTC, stefanvanherwijnen commented on packages/oidc-provider/src/OidcModule.ts
> +        this.app.use(mount("/oidc", provider.app));
> hum... let the user to configure the correct path from configuration could be a better options. Because today, /oidc isn't the default path and it will be a breaking change. no?

It is a breaking change, but the point is that the current implementation is incorrect in my opinion. Mounting oidc at / will make it impossible to use the TSed exception handler. For current users of oidc-provider and TSed this will break any manually configured clients, but if they use the .well-known route for endpoint discovery everything will still work (i.e. .well-known will point to the /oidc/* routes). For versioning this might be a problem, but I think it is a valid breaking change (or rather a 'fixing' change :grin: )

2021-08-17 08:19 UTC, stefanvanherwijnen commented on packages/oidc-provider/src/OidcModule.ts
> +    if (this.platformName === "koa") {
It is required according to the specifications of oidc (discovery document should be at the root path): https://github.com/panva/node-oidc-provider/blob/88fa711261401449292df5fa39d9349dd587120f/docs/README.md#to-a-koa-application

2021-08-17 08:22 UTC, Romakita commented on packages/oidc-provider/src/OidcModule.ts
> +    if (this.platformName === "koa") {
Ok ^^ Well if the doc says so: p

2021-08-17 08:24 UTC, Romakita commented
Thanks, one more thing which does not seem to work: the Post() routes in the interactions do not seem to get registered when using koa. E.g. POST to /interactions/123/login results in a NOT_FOUND error with koa, but with express it results in SessionNotFound as expected. The main GET routes do work fine.

Any clue?

Hue... I haven't idea. I would have to go back to the code and reproduce the error to be able to answer you

2021-08-17 09:46 UTC, stefanvanherwijnen commented
> Thanks, one more thing which does not seem to work: the Post() routes in the interactions do not seem to get registered when using koa. E.g. POST to /interactions/123/login results in a NOT_FOUND error with koa, but with express it results in SessionNotFound as expected. The main GET routes do work fine.
> 
> Any clue?
> 
> Hue... I haven't idea. I would have to go back to the code and reproduce the error to be able to answer you

The problem seems to be that any Controller routes in any of the children of the InteractionController are not registered when using koa. I guess it is a problem somewhere in @tsed/platform-koa and route registration, but I can't find exactly where things go wrong.
If I don't use the @Interaction but register a controller directly with @Controller it does work, so I think it's somewhere in @tsed/oidc-provider not registering the routes properly in combination with koa. The strange thing is that they do show up in the server log upon boot, but result in NOT_FOUND.

2021-08-17 12:22 UTC, stefanvanherwijnen commented on packages/oidc-provider/src/OidcModule.ts
> +
The basePath should not be the same as the interactions path. basePath (or /oidc) should point to the OIDC instance and the interactions should be on a separate route. I believe everything under /oidc is strictly specified by the OpenID Connect specification, and interactions are a user implementation.

2021-08-17 12:52 UTC, Romakita commented
> The problem seems to be that any Controller routes in any of the children of the InteractionController are not registered when using koa. I guess it is a problem somewhere in @tsed/platform-koa and route registration, but I can't find exactly where things go wrong.
> If I don't use the `@Interaction` but register a controller directly with `@Controller` it does work, so I think it's somewhere in @tsed/oidc-provider not registering the routes properly in combination with koa. The strange thing is that they do show up in the server log upon boot, but result in NOT_FOUND.

Haa ok. isn't normal. The custom interactions are mounted by oidc-provider from the configuration, by generating the policy options:
https://github.com/tsedio/tsed/blob/a22e24152523bcead7afdfefa63897a565ec9f90/packages/oidc-provider/src/services/OidcProvider.ts#L145

So, one of the explanation is oidc-provider have change something about custom interaction because, with express, the because with express it worked. With Koa, I don't know, but the principle should be the same. The policy provide an configuration abstraction...

I'll take a time to debug this issue ^^

2021-08-17 13:20 UTC, stefanvanherwijnen commented
I thought I fixed it, but `@Post(/login)` works in express but not koa, and `@Post(login)` works in koa but not express :sweat_smile: .
So I think it is a problem with [preceding slashes and koa](https://stackoverflow.com/questions/39666603/koa-router-issue-with-and-signin).

2021-08-18 06:17 UTC, Romakita commented
Arf... so we have to manage the slash with koa for all routes added by decorator ?

2021-08-18 06:18 UTC, Romakita commented
ok because appending "/" can generate a route with double "//" in a specific case.

2021-08-18 06:19 UTC, Romakita commented
I work on a new PR to remove koa-router and express-router, so I 'll try to fix this issue in the same time.

2021-08-18 09:18 UTC, stefanvanherwijnen commented
Great, thanks.

Would you be OK with having a manually configured basepath which defaults to / now but to /oidc in the next major version? That way things won't break now but will be working correctly in the future.

2021-08-18 09:19 UTC, Romakita commented
The next major version isn't planed but yes sure :) You can add a note in the documentation page to inform the dev to the future breaking change.

2021-08-18 16:30 UTC, Romakita requested changes

2021-08-18 16:30 UTC, Romakita commented on packages/oidc-provider/src/OidcModule.ts
> +        this.app.use(rewrite("/.well-known/(.*)", `${this.basePath}/.well-known/$1`));
hum if this path is "/" this rewrite url will be "//.well-known/$1" I think it's problematic

2021-08-19 08:39 UTC, stefanvanherwijnen commented on packages/oidc-provider/src/OidcModule.ts
> +        this.app.use(rewrite("/.well-known/(.*)", `${this.basePath}/.well-known/$1`));
It only rewrites if basepath is not "/" 😉

2021-08-19 08:40 UTC, Romakita commented on packages/oidc-provider/src/OidcModule.ts
> +        this.app.use(rewrite("/.well-known/(.*)", `${this.basePath}/.well-known/$1`));
haaa yes sorry.

2021-08-19 15:50 UTC, stefanvanherwijnen commented on packages/oidc-provider/src/OidcModule.ts
> +        this.app.use(rewrite("/.well-known/(.*)", `${this.basePath}/.well-known/$1`));
I added some tests to make sure it works correctly  :smile:

2021-08-20 07:32 UTC, Romakita approved these changes

2021-08-20 09:45 UTC, Romakita commented
@stefanvanherwijnen I pushed new unit test to cover the code ;)

2021-08-20 13:56 UTC, Romakita commented
I let you to test the latest change before merging the PR ;) @stefanvanherwijnen

2021-08-21 12:40 UTC, stefanvanherwijnen commented
Alright thanks. I'll get to it later.

2021-08-21 18:53 UTC, Romakita commented
I can merge it if it’s ok for you

2021-08-21 19:47 UTC, stefanvanherwijnen commented
There are a still a few inconsistencies in the docs. Let me fix them first.

2021-08-22 09:52 UTC, Romakita approved these changes

2021-08-22 09:53 UTC, stefanvanherwijnen commented
Everything seems correct now. I also PRed the CLI plugin so if both are merged one can select OpenID Connect provider as a feature and everything should work :smile: .

2021-08-22 09:57 UTC, Romakita commented
Great Job @stefanvanherwijnen I'll merge in few minutes your awesome works ;)

2021-08-22 12:50 UTC, merged

2021-08-22 13:08 UTC, Romakita commented
:tada: This PR is included in version 6.63.2 :tada:

The release is available on:
- `v6.63.2`
- [GitHub release](https://github.com/tsedio/tsed/releases/tag/v6.63.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: