feat(mongoose): migrate to jest
TypedProject/ts-express-decorators pull request #1560
Opened 2021-10-05 06:31 UTC by matthiasferraina

## Information

Type | Breaking change
---|---
Feature/Fix/Doc/Chore | Yes/No

****

## Todos

- [ ] Tests
- [ ] Coverage
- [ ] Example
- [ ] Documentation

2021-10-05 07:09 UTC, Romakita requested changes

2021-10-05 07:09 UTC, Romakita commented on packages/orm/mongoose/src/decorators/postHook.spec.ts
> -        @PostHook("save")
C’est bizarre que le test change ^^

2021-10-05 07:19 UTC, matthiasferraina commented on packages/orm/mongoose/src/decorators/postHook.spec.ts
> -        @PostHook("save")
effectivement ^^

2021-10-05 10:46 UTC, matthiasferraina commented on packages/orm/mongoose/src/decorators/postHook.spec.ts
> -        @PostHook("save")
j'ai corrigé le test en passant une option. le décorateur requiert au moins 2 arguments pour une métode de classe

2021-10-05 17:51 UTC, Romakita approved these changes

2021-10-05 17:51 UTC, merged

2021-10-06 12:08 UTC, Romakita commented
:tada: This PR is included in version 6.73.6 :tada:

The release is available on:
- `v6.73.6`
- [GitHub release](https://github.com/tsedio/tsed/releases/tag/v6.73.6)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: