fix(typeorm): fix cycling connections in typeorm when reinitializing
TypedProject/ts-express-decorators pull request #1595
Opened 2021-10-21 06:39 UTC by Oatelaus

I've reported this issue in slack, you'd notice this when actually connecting to the database in tests - possibly if you cycle the TypeORM Module when running your application.

Calling `PlatformTest.create/reset` would go down into the `init` and `$onDestroy` functions. On the second test run, it would check `this.has(name)` and return the previous instance where the connections had been closed.

2021-10-21 07:22 UTC, Romakita requested changes

2021-10-21 07:22 UTC, Romakita commented on packages/orm/typeorm/src/services/TypeORMService.ts
I suggest to refactoring the createConnnection function to ensure that the connection is alway connected :)

```
export async function createConnection(connectionOptions: ConnectionOptions): Promise<Connection> {
  const connectionManager = getConnectionManager();
  const name = getValue<string>(connectionOptions, "name", "default");

  if (!connectionManager.has(name)) {
    const connection = connectionManager.create(connectionOptions!);
    await connection.connect();
  }

  const connection = connectionManager.get(name);

  return connection;
}

```

And in the typeormService:
```
  @Inject(InjectorService)
  private injector: InjectorService;

  /**
   *
   * @returns {Promise<"typeorm".Connection>}
   */
  async createConnection(connectionOptions: ConnectionOptions): Promise<any> {
    try {
      const connection = await createConnection(connectionOptions);
      this.injector.logger.info(`Connected with typeorm to database: ${connection.name}`);

      return connection;
    } catch (err) {
      /* istanbul ignore next */
      console.error(err);
      /* istanbul ignore next */
      process.exit();
    }
  }

```

2021-10-21 07:32 UTC, Romakita approved these changes

2021-10-21 07:36 UTC, Fedelaus commented
I'll fix linting in a moment!

2021-10-22 15:04 UTC, merged

2021-10-23 04:43 UTC, Romakita commented
:tada: This PR is included in version 6.75.5 :tada:

The release is available on:
- `v6.75.5`
- [GitHub release](https://github.com/tsedio/tsed/releases/tag/v6.75.5)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: