WIP: feat(mongoose): Add an option to `Ref` for more accurate JsonSchema ...
TypedProject/ts-express-decorators pull request #1668
Opened 2021-12-01 18:52 UTC by ochrstn

Add an option to `Ref` for more accurate JsonSchema based on `Groups` and populated Refs

## Information

Type | Breaking change
---|---
Feature| No :pray:

****

## Usage example

⚠️  TODO ⚠️

## Todos

- [x] Tests
- [ ] Coverage
- [ ] Example
- [ ] Documentation

2021-12-04 09:39 UTC, Romakita requested changes

2021-12-04 09:39 UTC, Romakita commented on packages/orm/mongoose/src/decorators/ref.spec.ts
> +      @Ref(MyChildModel, {populatedGroups: ["group1", "group2"]})
I don't understand the goal of this option ? 
It's to solve the problem with the OneOf + Groups options ? If it's for that, We should fix the issue with Groups + OneOf/AllOf/etc... instead ?

In your, test I don't see the impact on the MyChildModel if the groups is given.

2021-12-04 09:39 UTC, Romakita commented on packages/specs/schema/src/utils/mapRefType.ts
> +import {JsonSchema, JsonSchemaOptions} from "..";
this import will create a Circular ref in the package ^^

2021-12-04 10:39 UTC, ochrstn commented on packages/orm/mongoose/src/decorators/ref.spec.ts
> +      @Ref(MyChildModel, {populatedGroups: ["group1", "group2"]})
The goal is different here.

Without this option the schema type of `@Ref` property (child1, child2, child3 in the test) is always oneOf $ref and string.

Based on the presence of the `populatedGroups` option and matching groups the oneOf schema can be limited to be either $ref or string. This should of course correspond to the populated and not populated fields from a mongoose query that gets returned from an endpoint.

It does not and should not impact the MyChildModel. Only the properties of the MyParentModel.

Resulting schema of the MyParentModel:

child1: Because the endpoint group and ref group is matching I assume that the developer populated the child1 property in a query and returning it from the endpoint. The schema should be generated to reflect that it can't be a string anymore in that case.

child2: The opposite. Not populated property should be reflected in the schema to be only of type string.

child3: option not given, works live before

```
{
        "type": "object",
        "properties": {
            "id": {
                "type": "string"
            },
            "child1": {
                "oneOf": [
                    {
                        "$ref": "#/definitions/MyChildModel"
                    }
                ]
            },
            "child2": {
                "oneOf": [
                    {
                        "type": "string",
                        "examples": [
                            "5ce7ad3028890bd71749d477"
                        ],
                        "description": "Mongoose Ref ObjectId"
                    }
                ]
            },
            "child3": {
                "oneOf": [
                    {
                        "type": "string",
                        "examples": [
                            "5ce7ad3028890bd71749d477"
                        ],
                        "description": "Mongoose Ref ObjectId"
                    },
                    {
                        "$ref": "#/definitions/MyChildModel"
                    }
                ]
            }
        },
        "definitions": {
            "MyChildModel": {
                "type": "object",
                "properties": {
                    "test": {
                        "type": "string"
                    }
                }
            }
        }
    }
```

2021-12-04 17:12 UTC, Romakita commented on packages/orm/mongoose/src/decorators/ref.spec.ts
> +      @Ref(MyChildModel, {populatedGroups: ["group1", "group2"]})
ok I understand :)

I pushed small changes on your branch ;). I let you to review the code.

2021-12-04 17:34 UTC, ochrstn commented on packages/orm/mongoose/src/decorators/ref.spec.ts
> +      @Ref(MyChildModel, {populatedGroups: ["group1", "group2"]})
Thanks for the help. It looks amazing now

2021-12-05 07:32 UTC, Romakita commented on packages/orm/mongoose/src/decorators/ref.spec.ts
> +      @Ref(MyChildModel, {populatedGroups: ["group1", "group2"]})
Last point is about the coverage over @tsed/schema ^^

2021-12-05 07:40 UTC, ochrstn commented on packages/orm/mongoose/src/decorators/ref.spec.ts
> +      @Ref(MyChildModel, {populatedGroups: ["group1", "group2"]})
I will take a look 👀

2021-12-06 10:29 UTC, merged

2021-12-06 10:30 UTC, Romakita commented
Merged ;)

2021-12-06 10:45 UTC, Romakita commented
:tada: This PR is included in version 6.95.0 :tada:

The release is available on:
- `v6.95.0`
- [GitHub release](https://github.com/tsedio/tsed/releases/tag/v6.95.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: