feat(mikro-orm): add support for MikroOrm
TypedProject/ts-express-decorators pull request #1688
Opened 2021-12-21 13:01 UTC by derevnjuk

## Information

Type | Breaking change
---|---
Feature | No

****

## Usage example

### Installation

To begin, install the MikroOrm module for TS.ED:
```bash
npm install --save @tsed/mikro-orm
npm install --save @mikro-orm/core
```

Then import `@tsed/mikro-orm` in your Server:

```typescript
import {Configuration} from "@tsed/common";
import {MikroOrmModule} from "@tsed/mikro-orm";

@Configuration({
    imports: [MikroOrmModule],
    mikroOrm: [
    {
      contextName: 'default',
      type: 'postgres',
      ...,

       entities: [
         `${__dirname}/entity/*{.ts,.js}`
       ]
    },
    {
       contextName: 'mongo',
       type: 'mongo',
       ...
    }
  ]
})
export class Server {

}
```

For more information about MikroOrm look his documentation [here](https://mikro-orm.io/docs);

### Obtain a connection

`Connection` decorator lets you retrieve an instance of MikroOrm Connection.

```typescript
import {Service, AfterRoutesInit} from "@tsed/common";
import {Connection} from "@tsed/mikro-orm";
import {MikroORM} from "@mikro-orm/core";

@Service()
export class UsersService {
    @Connection()
    private readonly connection!: MikroORM;

    async create(user: User): Promise<User> {

        // do something
        // ...
        // Then save
        await this.connection.em.persistAndFlush(user);
        console.log("Saved a new user with id: " + user.id);

        return user;
    }

    async find(): Promise<User[]> {
        const users = await this.connection.em.find(User, {});
        console.log("Loaded users: ", users);

        return users;
    }
}
```

### Use Entity with Controller

To begin, we need to define an Entity MikroOrm like this and use Ts.ED Decorator to define the JSON Schema.

```typescript
import {Property, MaxLength, Required} from "@tsed/common";
import {Entity, Property, PrimaryKey, Property as Column} from "@mikro-orm/core";

@Entity()
export class User {

    @PrimaryKey()
    @Property()
    id: number;

    @Column()
    @MaxLength(100)
    @Required()
    firstName: string;

    @Column()
    @MaxLength(100)
    @Required()
    lastName: string;

    @Column()
    @Mininum(0)
    @Maximum(100)
    age: number;
}
```

Now, the model is correctly defined and can be used with a [Controller](https://tsed.io/docs/controllers.html), [AJV validation](tutorials/ajv.md),
[Swagger](tutorials/swagger.md) and [MikroOrm](https://mikro-orm.io/docs/defining-entities).

We can use this model with a Controller like that:

```typescript
import {Controller, Post, BodyParams} from "@tsed/common";

@Controller("/users")
export class UsersCtrl {

    constructor(private usersService: UsersService) {

    }

    @Post("/")
    create(@BodyParams() user: User): Promise<User> {

        return this.usersService.create(user);
    }

    @Get("/")
    getList(): Promise<User[]> {

        return this.usersService.find();
    }
}
```

### Transactions and Request context

As mentioned in the [docs](https://mikro-orm.io/docs/identity-map), we need to isolate a state for each request. That is handled automatically thanks to the `AsyncLocalStorage` registered via interceptor.

We can use the `@Transactional()` decorator, which will register a new request context for your method and execute it inside the context.

```typescript
import {Controller, Post, BodyParams} from "@tsed/common";
import {Transactional} from "@tsed/mikro-orm";

@Controller("/users")
export class UsersCtrl {

    constructor(private usersService: UsersService) {

    }

    @Post("/")
    @Transactional()
    create(@BodyParams() user: User): Promise<User> {

        return this.usersService.create(user);
    }

    @Get("/")
    getList(): Promise<User[]> {

        return this.usersService.find();
    }
}
```

## Appendix

`ts-mockito` mocking library is used in unit tests as a convenient way to work with test doubles.

## Todos

- [x] Tests
- [ ] Coverage
- [ ] Example
- [x] Documentation

closes #1547

2021-12-23 13:34 UTC, Romakita commented
Awesome @derevnjuk ,

I’ll take a time tomorrow to review the and give you the feedback ;)

great job!
Romain

2021-12-24 13:30 UTC, Romakita requested changes

2021-12-24 13:30 UTC, Romakita commented on packages/orm/mikro-orm/src/interceptors/TransactionalInterceptor.spec.ts
> +    when(mikroOrm.em).thenReturn(instance(entityManagerMock));
Is there a reason to not use jest ?

2021-12-24 13:30 UTC, Romakita commented on packages/orm/mikro-orm/src/MikroOrmModule.ts
> +registerProvider({
This part make me confused. You don't need to registerProvider as factory if it's a class. I prefer to use the decorator `@Injectable` and use the class as Token instead of declaring a Symbol ^^.

```typescript
@Injectable()
export class MikroOrmFactory {

}
```

2021-12-24 13:30 UTC, Romakita commented on packages/orm/mikro-orm/src/MikroOrmModule.ts
> +  private readonly settings: Options[];
```diff
+ @Constant("mikroOrm", [])
private readonly settings: Options[];

+ @Inject()
+ private readonly mikroOrmRegistry: MikroOrmRegistry;

- constructor(private readonly mikroOrmRegistry: MikroOrmRegistry) {
-    this.settings = configuration.get<Options[]>("mikroOrm", []);
- }

2021-12-24 13:30 UTC, Romakita commented on packages/orm/mikro-orm/src/services/MikroOrmRegistry.ts
> +    await Promise.all(connections.map((connection: MikroORM) => this.dispose(connection)));
```typescript
  public async closeConnections(): Promise<void> {
    const connections = [...this.connections.values()];

    await Promise.all(connections.map((connection: MikroORM) => catchAsyncError(() => this.dispose(connection))));

    this.connections.clear();
  }

  private async dispose(connection: MikroORM): Promise<void> {
    if (await connection.isConnected()) {
      await connection.close(false);
    }
  }
}
```

2021-12-24 13:30 UTC, Romakita commented on packages/orm/mikro-orm/test/integration.spec.ts
> +describe("TypeORM integration", () => {
MikroORM integration :)

2021-12-24 13:30 UTC, Romakita commented on packages/orm/mikro-orm/jest.config.js
> +      branches: 70,
don't hesite to set the coverage with the correct result ;)

2021-12-24 13:32 UTC, Romakita commented
Hello @derevnjuk 

Nice PR and nice works ;) Just small changes but the PR is almost ready to be merged!

See you ;)

2021-12-26 10:26 UTC, derevnjuk commented
@Romakita I'm glad to hear that, thank you 😄

2021-12-26 10:48 UTC, derevnjuk commented on packages/orm/mikro-orm/src/interceptors/TransactionalInterceptor.spec.ts
> +    when(mikroOrm.em).thenReturn(instance(entityManagerMock));
`ts-mockito` mocking library provides a more convenient way to work with test doubles, e.g.

```ts
const injectorServiceMock = {
  get: jest.fn()
};

injectorServiceMock.get.mockReturnValue({})
```

vs

```ts
const injectorServiceMock = mock<InjectorService>();

when(injectorServiceMock.get(anything())).thenReturn({})
```

As you can see, it makes it possible to control test values during a test according to input arguments.

In addition, unlike `jest`  it allows us to mock interfaces as well.

If you prefer to use `jest` mocks, I can rework tests to align with the existing code.

2021-12-26 10:50 UTC, Romakita commented on packages/orm/mikro-orm/src/interceptors/TransactionalInterceptor.spec.ts
> +    when(mikroOrm.em).thenReturn(instance(entityManagerMock));
No it’s fine. Maybe I’ll try to use it in future ^^

2021-12-26 10:56 UTC, derevnjuk commented on packages/orm/mikro-orm/src/MikroOrmModule.ts
> +registerProvider({
I prefer to use symbols to ensure the DI principle (SOLID). It lets us switch implementations without making patching in consumers. However, in this particular case, it doesn't matter, I do not think we someday introduce a new factory. We can rework it as you suggest.

2021-12-26 13:21 UTC, derevnjuk commented
@Romakita btw, it seems `PlatformTest.invoke` does not work as expected. It refuses to inject a mock implementation of `MikroOrmRegistry`:

```ts
const mdl: MikroOrmModule = await PlatformTest.invoke(MikroOrmModule, [
  {
    token: MikroOrmRegistry,
    use: {} as unknown as MikroOrmRegistry
  }
]);
```

Could you elaborate a bit, maybe, I'm doing something wrong? See example below:

```ts
describe("MikroOrmModule", () => {
  const mockMikroOrmRegistry = mock(MikroOrmRegistry);
  const config: Options = {
    type: "mongo",
    entities: [],
    clientUrl: "mongo://localhost"
  };

  beforeEach(() =>
    PlatformTest.create({
      mikroOrm: [config]
    })
  );

  afterEach(() => {
    reset(mockMikroOrmRegistry);

    return PlatformTest.reset();
  });

  describe("$onInit", () => {
    it("should create the corresponding connections", async () => {
      // arrange
      const mdl: MikroOrmModule = await PlatformTest.invoke(MikroOrmModule, [
        {
          token: MikroOrmRegistry,
          use: instance(mockMikroOrmRegistry)
        }
      ]);
      when(mockMikroOrmRegistry.createConnection(config)).thenResolve(({} as unknown) as MikroORM);

      // act
      await mdl.$onInit();

      // assert
      verify(mockMikroOrmRegistry.createConnection(config)).once();
    });
  });

  describe("$onDestroy", () => {
    it("should destroy the corresponding connections", async () => {
      // arrange
      const mdl: MikroOrmModule = await PlatformTest.invoke(MikroOrmModule, [
        {
          token: MikroOrmRegistry,
          use: instance(mockMikroOrmRegistry)
        }
      ]);
      when(mockMikroOrmRegistry.closeConnections()).thenResolve();

      // act
      await mdl.$onDestroy();

      // assert
      verify(mockMikroOrmRegistry.closeConnections()).once();
    });
  });
});

```

2021-12-27 09:08 UTC, Romakita approved these changes

2021-12-27 12:20 UTC, Romakita commented
@derevnjuk I can merge this PR. Then you can test it with a real project and add fix if it’s necessary. If all is ok for you, tell me and I’ll add a new doc page for mikro orm based on the readme.

thanks for your contrib ;)

2021-12-27 12:31 UTC, derevnjuk commented
@Romakita yeah, I don't have any objections) You can merge it

2021-12-27 17:50 UTC, merged

2021-12-27 17:50 UTC, Romakita commented
Done :D

2021-12-27 18:06 UTC, Romakita commented
:tada: This PR is included in version 6.96.0 :tada:

The release is available on:
- `v6.96.0`
- [GitHub release](https://github.com/tsedio/tsed/releases/tag/v6.96.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: