fix(json-mapper): fix serialization of additional properties
TypedProject/ts-express-decorators pull request #1762
Opened 2022-02-13 11:07 UTC by KODIKAS-NL

Serialization of additional properties if @additionalProperties(true) decorator is set on Model

## Information

Type | Breaking change
---|---
Fix | No

****
I expected the addition of the @additionalProperties decorator to a Model to also allow serialization of any additional properties but it didn't. This changes fixes this.

2022-02-14 07:05 UTC, Romakita requested changes

2022-02-14 07:05 UTC, Romakita commented on packages/specs/json-mapper/src/utils/serialize.ts
> +
```typescript
const additionalProperties = !!entity.schema.get("additionalProperties");
const schemaProperties = getSchemaProperties(entity, obj);
const properties = new Set<string>()
const out: any = schemaProperties.reduce((newObj, [key, propStore]) => {
    properties.add(key);
    
    // ...
})

 if (additionalProperties) {
    objectKeys(obj).forEach((key: any) => {
       if (!properties.has(key)) {
          out[key] = obj[key];
       }
    });
  }
```

2022-02-14 07:07 UTC, Romakita requested changes

2022-02-14 07:07 UTC, Romakita commented on packages/specs/json-mapper/src/utils/serialize.spec.ts
> +    it("should not serialize model with additonal object props", () => {
should not serialize model with **additional** object props

2022-02-14 07:07 UTC, Romakita commented on packages/specs/json-mapper/src/utils/serialize.spec.ts
> +    it("should serialize model with additonal object props", () => {
should serialize model with **additional** object props

2022-02-14 07:07 UTC, Romakita commented
Hello @KODIKAS-NL 
Thanks for this first PR ;)

Just minor changes! 
See you
Romain

2022-02-14 08:17 UTC, KODIKAS-NL commented on packages/specs/json-mapper/src/utils/serialize.ts
> +
This one gives me an error because the 'key' parameter in reduce is typed as 'string | number | symbol' :
<img width="713" alt="image" src="https://user-images.githubusercontent.com/58047787/153824210-b67a5006-645b-403f-86ba-369d452d8ec4.png">
I can solve this in one of 3 ways:
```suggestion
const properties = new Set<any>()
```
or
```suggestion
properties.add(key as string);
```
or
```suggestion
properties.add(key.toString());
```

Which do you prefer ?

2022-02-14 08:17 UTC, KODIKAS-NL commented on packages/specs/json-mapper/src/utils/serialize.spec.ts
> +    it("should not serialize model with additonal object props", () => {
😬

2022-02-14 08:22 UTC, Romakita commented on packages/specs/json-mapper/src/utils/serialize.ts
> +
properties.add(key as string);

is fine for me :)

2022-02-14 08:35 UTC, Romakita approved these changes

2022-02-14 08:54 UTC, merged

2022-02-14 09:14 UTC, Romakita commented
:tada: This PR is included in version 6.102.1 :tada:

The release is available on:
- `v6.102.1`
- [GitHub release](https://github.com/tsedio/tsed/releases/tag/v6.102.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-04-12 07:35 UTC, Romakita commented
:tada: This PR is included in version 7.0.0-beta.4 :tada:

The release is available on:
- `v7.0.0-beta.4`
- [GitHub release](https://github.com/tsedio/tsed/releases/tag/v7.0.0-beta.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: