feat(keycloak): add keycloak module
TypedProject/ts-express-decorators pull request #1773
Opened 2022-02-19 19:34 UTC by xCryzed

## Information

| Type                  | Breaking change |
| --------------------- | --------------- |
| Feature | No          |

---

WIP

2022-02-20 08:24 UTC, Romakita requested changes

2022-02-20 08:24 UTC, Romakita commented on packages/third-parties/keycloak/package.json
> +  "main": "./lib/cjs/index.js",
"module": "./lib/esm/index.js"  

I'll add it for other modules in another PR ;)

2022-02-20 08:24 UTC, Romakita commented on packages/third-parties/keycloak/package.json
> +    "keycloak-connect": "17.0.0"
"keycloak-connect": ">=17.0.0"

2022-02-20 08:24 UTC, Romakita commented on packages/third-parties/keycloak/src/KeycloakModule.ts
> +    return undefined;
probably, it's not finish here ^^

2022-02-20 08:24 UTC, Romakita commented on packages/third-parties/keycloak/src/index.ts
> +        kcOptions?: KeycloakOptions;
options?: KeycloakOptions;

where are already in keycloak objet ^^

2022-02-20 08:24 UTC, Romakita commented on packages/third-parties/keycloak/src/index.ts
> +        kcConfig: KeycloakConfig | string;
config: KeycloakConfig | string;

2022-02-21 07:47 UTC, xCryzed commented on packages/third-parties/keycloak/package.json
> +    "keycloak-connect": "17.0.0"
Done

2022-02-21 17:36 UTC, Romakita requested changes

2022-02-21 17:36 UTC, Romakita commented on packages/third-parties/keycloak/README.md
> +
The readme is incomplete :)

2022-02-21 17:36 UTC, Romakita commented on packages/third-parties/keycloak/README.md
> +
You can take the stripe readme as example ^^

2022-02-21 17:36 UTC, Romakita commented on packages/third-parties/keycloak/src/index.ts
> +import {KeycloakConfig, KeycloakOptions} from "keycloak-connect";
can you move the `declare global` code part in `interfaces/interfaces.ts`. The RC branch change the directory structures do be compliant with ESM module :)

2022-03-29 03:04 UTC, Romakita approved these changes

2022-03-29 03:04 UTC, Romakita commented
@xCryzed is it ready?

2022-03-29 07:42 UTC, xCryzed commented
@Romakita we still need tests and a little bit more documenation.

2022-12-31 21:03 UTC, closed without merging