Fix: a few possible errors in the PlatformHandler.onError method
TypedProject/ts-express-decorators pull request #1814
Opened 2022-03-19 13:53 UTC by AlexDede

## Information

| Type                  | Breaking change |
| --------------------- | --------------- |
| Fix | No          |

---

Fixed: #1812

2022-03-19 14:21 UTC, Romakita requested changes

2022-03-19 14:21 UTC, Romakita commented on packages/platform/common/src/services/PlatformHandler.ts
> +    return next(er);
next is not always given, it depend on how the handler have been built. Can you revert this change please ;)

2022-03-19 14:29 UTC, AlexDede commented on packages/platform/common/src/services/PlatformHandler.ts
> +    return next(er);
This method throws the error if `next` is not defined a few lines above

2022-03-19 14:31 UTC, AlexDede commented on packages/platform/common/src/services/PlatformHandler.ts
> +    return next(er);
So I can revert this line but in this case, I should remove

``` js
 if (!next) {
    throw er;
 }
```

2022-03-19 18:41 UTC, Romakita approved these changes

2022-03-19 18:41 UTC, Romakita commented on packages/platform/common/src/services/PlatformHandler.ts
> +    return next(er);
You’ve right.

2022-03-19 18:41 UTC, merged

2022-03-19 19:01 UTC, Romakita commented
:tada: This PR is included in version 6.107.4 :tada:

The release is available on:
- `v6.107.4`
- [GitHub release](https://github.com/tsedio/tsed/releases/tag/v6.107.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-04-12 07:34 UTC, Romakita commented
:tada: This PR is included in version 7.0.0-beta.4 :tada:

The release is available on:
- `v7.0.0-beta.4`
- [GitHub release](https://github.com/tsedio/tsed/releases/tag/v7.0.0-beta.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: