docs: fixing broken links
TypedProject/ts-express-decorators pull request #1843
Opened 2022-04-04 16:00 UTC by sofianeSghiouar

## Information

| Type                  | Breaking change |
| --------------------- | --------------- |
| Feature/Fix/Doc/Chore | Yes/No          |

---

## Todos

- [ ] Tests
- [ ] Coverage
- [ ] Example
- [ ] Documentation

2022-04-04 16:13 UTC, Romakita requested changes

2022-04-04 16:13 UTC, Romakita commented on docs/getting-started/README.md
> +- [Use functional programming to declare custom schema](/docs/models.md#using-functions).  <!--- dead link --->
/docs/model.md

tu dois avoir une section dans la page qui correspond au hash tag. Le soucis c'est que le titre a peut etre changé et donc le hastag aussi

2022-04-04 16:13 UTC, Romakita commented on docs/docs/validation.md
> +Ts.ED provide by default a [AJV](/tutorials/ajv.md) package `@tsed/ajv` to perform a validation on a [Model](/docs/models.md).
/docs/model.md

2022-04-04 16:13 UTC, Romakita commented on docs/tutorials/ajv.md
> +<Banner src="../.vuepress/public/ajv_logo.png" href="https://ajv.js.org/" height="100" />
/ajv_logo.png

2022-04-04 16:13 UTC, Romakita commented on docs/tutorials/ajv.md
> +<Banner src="../.vuepress/public/ajv_logo.png" href="https://ajv.js.org/" height="100" />
tout ce qui est dans public est exposé à la racine du domaine.

2022-04-04 16:13 UTC, Romakita commented on docs/tutorials/mikroorm.md
> +, [AJV validation](ajv.md),
/tutorials/ajv.md

2022-04-04 16:13 UTC, Romakita commented on docs/tutorials/mikroorm.md
> +[Swagger](swagger.md) and [MikroORM](https://mikro-orm.io/docs/defining-entities).
/tutorials/swagger.md

2022-04-04 16:13 UTC, Romakita commented on docs/tutorials/socket-io.md
> +<Banner src="../.vuepress/public/socketio_logo.png" href="https://socket.io" height="180" style="margin-left:-40px" />
/socketio_logo.png

2022-04-05 15:15 UTC, Romakita approved these changes

2022-04-05 16:34 UTC, sofianeSghiouar commented on docs/tutorials/mikroorm.md
> +[Swagger](swagger.md) and [MikroORM](https://mikro-orm.io/docs/defining-entities).
Quand je fait un control + click sur (/tutorials/swagger.md) ça génère une erreur alors que la même manip avec (../tutorials/swagger.md)  ça marche.  Ou encore (swagger.md) marche aussi avec le control + click. Tout pareil pour (tutorials/ajv.md)

2022-04-05 17:21 UTC, Romakita commented on docs/tutorials/mikroorm.md
> +[Swagger](swagger.md) and [MikroORM](https://mikro-orm.io/docs/defining-entities).
Les chemins sont relatif au nom de domain et ton host. Ne te fie surtt pas à ton ide dans ce cas ci. Le seul moyen de le valider, c’est de lancer le site et cliquer sur le lien. Fais moi confiance!

2022-04-07 05:17 UTC, Romakita approved these changes

2022-04-07 05:17 UTC, Romakita commented
Faut que tu rebases ta branche par rapport à production ;) et on sera bon pour la merger :p

2022-04-08 07:31 UTC, merged

2022-04-11 06:31 UTC, Romakita commented
:tada: This PR is included in version 6.111.0 :tada:

The release is available on:
- `v6.111.0`
- [GitHub release](https://github.com/tsedio/tsed/releases/tag/v6.111.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-04-12 07:33 UTC, Romakita commented
:tada: This PR is included in version 7.0.0-beta.4 :tada:

The release is available on:
- `v7.0.0-beta.4`
- [GitHub release](https://github.com/tsedio/tsed/releases/tag/v7.0.0-beta.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: