feat(mikro-orm): introduce middleware to isolate the request context
TypedProject/ts-express-decorators pull request #1950
Opened 2022-06-20 18:16 UTC by derevnjuk

## Information

| Type                  | Breaking change |
| --------------------- | --------------- |
| Feature | No          |

---

## Usage example

Please refer to #1949 for details.

## Todos

- [ ] Tests
- [ ] Coverage
- [ ] Example
- [ ] Documentation

closes #1949

2022-06-20 19:56 UTC, Romakita requested changes
Hello @derevnjuk 
Nice PR. I just saw that this PR is draft but I already added some comments ;)

see you 
Romain

2022-06-20 19:56 UTC, Romakita commented on packages/orm/mikro-orm/package.json
> +    "@tsed/async-hook-context": "^6.114.17",
This package isn’t required anymore since the hook context is integrated to tsed/di

2022-06-20 19:56 UTC, Romakita commented on packages/orm/mikro-orm/src/services/MikroOrmEntityManagers.ts
> +  private get context(): DIContext | undefined {
The @InjectContext should do the job no?

2022-06-20 19:56 UTC, Romakita commented on packages/orm/mikro-orm/src/services/MikroOrmEntityManagers.ts
> +    if (AsyncLocalStorage) {
Create storage is not necessary if your goal is just to retrieve context. InjectContext is here for that ^^

2022-06-20 19:56 UTC, Romakita commented on packages/orm/mikro-orm/src/services/MikroOrmEntityManagers.ts
> +  public set(em: EntityManager | EntityManager[]): this {
[].concat(em) ?

2022-06-20 19:56 UTC, Romakita commented on packages/orm/mikro-orm/src/middlewares/MikroOrmContextMiddleware.ts
> +  constructor(@Inject() private readonly store: MikroOrmEntityManagers, @Inject() private readonly registry: MikroOrmRegistry) {}
Proposal: store => managers ?

2022-06-21 10:52 UTC, derevnjuk commented on packages/orm/mikro-orm/src/services/MikroOrmEntityManagers.ts
> +    if (AsyncLocalStorage) {
You are right. It should work well if we consider that it is used only with controllers. However, if we speak about Agenda (https://tsed.io/tutorials/agenda.html#create-a-new-service), the context will be null or undefined. I'm going to sort out how to handle both cases)

2022-06-21 10:56 UTC, derevnjuk commented on packages/orm/mikro-orm/src/services/MikroOrmEntityManagers.ts
> +  public set(em: EntityManager | EntityManager[]): this {
This implies casting `[]` to `EntityManger[]`, otherwise tsc raises compile-time error due to `ConcatArray`

```ts
const managers = ([] as EntityManager[]).concat(em);
```

2022-06-21 11:37 UTC, Romakita commented on packages/orm/mikro-orm/src/services/MikroOrmEntityManagers.ts
> +    if (AsyncLocalStorage) {
The context is always initiate by the controller and especially by the DI. There is no other case that the context could be available or created by something else.

2022-06-21 13:07 UTC, derevnjuk commented on packages/orm/mikro-orm/src/services/MikroOrmEntityManagers.ts
> +    if (AsyncLocalStorage) {
This is true if we speak about `DIContext`. But in the case of orm, we should have an async context to isolate, handle and propagate transactions between different repositories and service methods. The current implementation doesn't allow us to do that, that is why PR is still in draft)

As shown in the example below, we expect that a fork will be used. `@UseRequestContext` acts as interception running `sendAdminStatistics` inside an async context and creating a fork in the background.

```
@Agenda({ namespace: "email" })
export class EmailJobService {
  @Orm()
  private readonly orm!: MikroOrm;

  @Every("60 minutes", {
    name: "maintenanceJob",
    /* ... and any option you would normally pass to agenda.every/define */ }
  })
  @UseRequestContext()
  async sendAdminStatistics(job: Job) {
    const admin = this.orm.em.findOne(User, {admin: true})

    // do something
  }
}
```
Once we replace the `@UseRequestContext` decorator with the current implementation of `@Transactional`, it won't work anymore due to the lack of `DIContext`. The previous one that used `DBContext` works well.

To understand the main issue, let's considered another example:

```ts
@Middleware()
export class MikroOrmContextMiddleware implements MiddlewareMethods {

  constructor(@Inject() private readonly registry: MikroOrmRegistry) {}

  public use(@Next() next: (...args: unknown[]) => void): void {
    const instances = [...this.registry.values()];
    const entityManagers = instances.map((orm) => orm.em);

    RequestContext.create(entityManagers, next);
  }
}

@Controller('/')
export class UserController {
  @Em() private readonly em!: EntityManager;

  @Get()
  @Use(MikroOrmContextMiddleware)
  public getAll(): Promise<void> {
    return this.em.find(User, {});
  }
}
```

Here we use the build-in `RequestContext` provided by `mikro-orm` to run the middleware sequence inside the same async context. However, it won't work as well since `PlatformHandler` is losing a context created by `RequestContext`. 

That means we should either sort out of how to use different instances of async local stores, or rework `PlatformHandler` to prevent losing context (then we can use build-in `RequestContext` from `mikro-orm`).

2022-06-22 20:09 UTC, Romakita commented on packages/orm/mikro-orm/src/services/MikroOrmEntityManagers.ts
> +    if (AsyncLocalStorage) {
Ok for the example with Agenda it make sense because agenda run code outside a RequestContext. RequestContext come from mikro orm right ? if it's from `@tsed/mikro-orm` the decorator name is confusing for me, because, in your example, it's a not request context (the request/response are missing) while the name seems to indicate that it is.

The name must be different, and should reflect the intent to create a context in order to execute the code in it.

> Here we use the build-in RequestContext provided by mikro-orm to run the middleware sequence inside the same async context. However, it won't work as well since PlatformHandler is losing a context created by RequestContext.

Ok I understand. It make sense if you want to create multiple context and isolated transaction, independently from each other.

2022-06-24 09:46 UTC, Romakita approved these changes

2022-06-24 09:56 UTC, Romakita requested changes

2022-06-24 09:56 UTC, Romakita commented on packages/orm/mikro-orm/src/MikroOrmModule.ts
> +    this.app.use((req: Req, res: Res, next: Next) => this.createContext(next));
This instruction won't work with Koa.

I think we need to find another way to wrap the context correctly.

2022-06-24 09:56 UTC, Romakita commented on packages/orm/mikro-orm/src/MikroOrmModule.ts
> +    this.app.use((req: Req, res: Res, next: Next) => this.createContext(next));
I have to rework the PlatformHandler to run the next method inside a context right ? or give you way to wrap each handler in a context.

2022-06-24 11:01 UTC, Romakita commented on packages/orm/mikro-orm/src/MikroOrmModule.ts
> +    this.app.use((req: Req, res: Res, next: Next) => this.createContext(next));
With this https://github.com/tsedio/tsed/pull/1957
You'll able to wrap the next function with the appropriate hook :)

```typescript
$alterRunInContext(next, $ctx) {
  return this.createContext(next)
}
```

2022-06-24 11:18 UTC, derevnjuk commented on packages/orm/mikro-orm/src/MikroOrmModule.ts
> +    this.app.use((req: Req, res: Res, next: Next) => this.createContext(next));
We can easily overload this middleware to cover both cases:

```
interface RawMiddleware {
  (req: Express.Request, res: Express.Response, next: Express.NextFunction): unknown;

  (context: Koa.Context, next: Koa.Next): unknown;
}

const rawMiddleware: RawMiddleware = (reqOrContext: Express.Request | Koa.Context, resOrNext: Express.Response | Koa.Next, next?: Express.NextFunction) =>
  this.createContext(next ?? resOrNext);

this.app.use(rawMiddleware);
```

This is not the best solution but should work.

> I have to rework the PlatformHandler to run the next method inside a context 

This may solve the initial issue. If it is possible to do with minimum effort, I would prefer to follow this solution.

2022-06-24 11:56 UTC, derevnjuk commented on packages/orm/mikro-orm/src/MikroOrmModule.ts
> +    this.app.use((req: Req, res: Res, next: Next) => this.createContext(next));
@Romakita as soon as we rework `runInContext` as follows:

```
runInContext(next: Function) {
  return runInContext(this, () => this.injector.alterAsync("$alterRunInContext", next, this));
}
```

It should work properly. So, I guess we can confidently proceed with this approach

2022-06-24 12:39 UTC, Romakita commented on packages/orm/mikro-orm/src/MikroOrmModule.ts
> +    this.app.use((req: Req, res: Res, next: Next) => this.createContext(next));
true :)

2022-06-24 12:45 UTC, Romakita commented on packages/orm/mikro-orm/src/MikroOrmModule.ts
> +    this.app.use((req: Req, res: Res, next: Next) => this.createContext(next));
here is the right code:

```typescript
    return runInContext(this, () => {
      next = this.injector.alter("$alterRunInContext", next, this)
      return next()
    });
```

And in your module, it should be written as follow:
```typescript
$alterRunInContext(next, $ctx) {
  return () => this.createContext(next)
}
```

2022-06-24 12:57 UTC, Romakita commented on packages/orm/mikro-orm/src/MikroOrmModule.ts
> +    this.app.use((req: Req, res: Res, next: Next) => this.createContext(next));
Seems to be ready :
https://github.com/tsedio/tsed/pull/1957 :)

2022-06-25 06:30 UTC, Romakita commented on packages/orm/mikro-orm/src/MikroOrmModule.ts
> +    this.app.use((req: Req, res: Res, next: Next) => this.createContext(next));
Merged :)

2022-06-25 15:12 UTC, Romakita approved these changes

2022-06-26 07:52 UTC, Romakita commented
PR seems to be ok for me @derevnjuk . Can I merge it ? Documentation is up to date ?

See you
Romain

2022-06-26 07:54 UTC, Romakita commented
maybe it's a time to finish this doc on mikro-orm, now that the module is on mikro-orm v5?

https://github.com/mikro-orm/mikro-orm/pull/2587

2022-06-30 06:35 UTC, derevnjuk commented
@Romakita documentation is up to date, you can merge PR without any issues

2022-06-30 15:40 UTC, merged

2022-06-30 16:34 UTC, Romakita commented
:tada: This PR is included in version 6.116.0 :tada:

The release is available on:
- `v6.116.0`
- [GitHub release](https://github.com/tsedio/tsed/releases/tag/v6.116.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-07-25 18:55 UTC, Romakita commented
:tada: This PR is included in version 7.0.0-beta.13 :tada:

The release is available on:
- `v7.0.0-beta.13`
- [GitHub release](https://github.com/tsedio/tsed/releases/tag/v7.0.0-beta.13)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: