Fix peerDep of @prisma/client to match dependency
TypedProject/ts-express-decorators pull request #2023
Opened 2022-08-05 10:03 UTC by martin31821

## Information

| Type                  | Breaking change |
| --------------------- | --------------- |
| Chore | No          |

2022-08-05 11:06 UTC, Romakita requested changes

2022-08-05 11:06 UTC, Romakita commented on packages/orm/prisma/package.json
> +    "@prisma/client": "^4.0.0",
It should be >=4.0.0

2022-08-05 11:16 UTC, martin31821 commented on packages/orm/prisma/package.json
> +    "@prisma/client": "^4.0.0",
Should I change all deps to >=4.0.0 then?

2022-08-05 12:20 UTC, Romakita commented on packages/orm/prisma/package.json
> +    "@prisma/client": "^4.0.0",
no just for the deep dependencies, to allow future major version.

2022-08-05 12:49 UTC, Romakita approved these changes

2022-08-05 12:49 UTC, merged

2022-08-05 13:13 UTC, Romakita commented
:tada: This PR is included in version 6.125.2 :tada:

The release is available on:
- `v6.125.2`
- [GitHub release](https://github.com/tsedio/tsed/releases/tag/v6.125.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-08-21 13:24 UTC, Romakita commented
:tada: This PR is included in version 7.0.0-beta.18 :tada:

The release is available on:
- `v7.0.0-beta.18`
- [GitHub release](https://github.com/tsedio/tsed/releases/tag/v7.0.0-beta.18)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: