feat(objection): add model relationship decorators
TypedProject/ts-express-decorators pull request #2078
Opened 2022-09-03 23:33 UTC by rossyman

## Information

| Type      | Breaking change |
| ------------------| ------- |
| Feature | No          |

First time contributor here 😄  If there are any striking concerns about this PR then please let me know, as I'm happy to work on it. I thought that it'd be useful to use decorators to describe relationships via Objection.

This PR _hopefully_ honours the way that Objection's Graph and Relationship Querying APIs work -- whilst also ensuring the consumer's domain model is a bit more strict, by actually defining related properties on an entity as optional, instead of only loosely defining them via `relationMappings`.

---

## Usage example

```typescript
/**
 * All work in a similar manner:
 * - @HasMany, @HasOne, @HasOneThroughRelation, @ManyToMany, @RelatesTo
 */
import { BelongsToOne } from '@tsed/objection';

@Entity('animal')
class Animal extends Model {

  id!: string;

  @BelongsToOne(Person, {
    join: {from: "animal.id", to: "person.id"}
  })
  owner?: Person;
}

const owner = await Animal.relatedQuery('owner').for(1);
```

## Todos

- [x] Tests
- [x] Coverage
- [x] Example
- [ ] Documentation

2022-09-03 23:47 UTC, rossyman commented
Some extra thought I had on this PR:
- It would be nice if we could infer the `modelClass` from the type defined on the property (Not even sure if this is possible)
- It would be nice if we could make the join options supplied to this decorator less nested

2022-09-04 17:33 UTC, rossyman commented
Last thought I had on this, was that:
- [ ] It would be nice if we could set a _responsible_ default for relationship joins
    - i.e.: from/to `${target.tableName}.${target.idColumn}` ~ from/to `${classModel.tableName}.${classModel.idColumn}` and allow optional overriding instead of mandatory parameters.

2022-09-05 05:40 UTC, Romakita approved these changes

2022-09-05 05:40 UTC, Romakita commented on packages/orm/objection/src/decorators/relatesTo.spec.ts
> +      @RelatesTo(Model.BelongsToOneRelation)
Not sure to understand the differentes between BelongsToOne and this decorator.

Why need to give `Model.BelongsToOneRelation` as parameter ?

It could be default value for the first parameter ?

2022-09-05 05:40 UTC, Romakita commented on packages/orm/objection/src/decorators/relatesTo.spec.ts
> +      @RelatesTo(Model.BelongsToOneRelation)
Ok RelatesTo is a technical decorator for others decorators. ^^

2022-09-05 05:41 UTC, Romakita commented
Hello @rossyman,

It seems to be ok for me :) Good PR. 

The documentation over the new decorators is missing. Don't forget to add it in /docs/tutorials/objection.md ;)

See you
Romain

2022-09-05 11:16 UTC, rossyman commented
Updated the documentation and fixed the build/test phase -- One point, is that I'm not sure what I need to do for `viewpress` to find these new decorators, as at the moment, they're not showing up in the `<ApiList>` component in the markdown.

2022-09-05 11:48 UTC, Romakita commented
@rossyman you can take as example the mongoose.md where the ApiList is used to display mongoose decorators ;)

2022-09-05 12:26 UTC, rossyman commented
Ah okay so it seems the API is queried from `tsed.io` -- So makes sense these don't show up yet as they're not released.

2022-09-06 05:25 UTC, Romakita commented
> Ah okay so it seems the API is queried from tsed.io -- So makes sense these don't show up yet as they're not released.

It's possible to regenerate locally the api.json file by running the command: `yarn docs:serve`. But this command, works only on linux/mac Os.

I'll checkout your PR to verify if the ApiList is correctly configured for Objection page.

See you
Romain

2022-09-06 09:25 UTC, rossyman commented
Tests are running into an issue with array types. Sadly this issue (https://github.com/microsoft/TypeScript/issues/7169) has been open for 6 years now, so I'll add in some extra parameters to the configuration for relationships that are plural to expose this type.

2022-09-06 10:34 UTC, rossyman commented
I can now confirm that the tests and docs are all building / passing correctly 😄 

![Screenshot 2022-09-06 at 11 33 17](https://user-images.githubusercontent.com/10212476/188613911-3c8c1bfb-173e-4532-9ee4-1b48a3695da9.png)

![Screenshot 2022-09-06 at 11 25 13](https://user-images.githubusercontent.com/10212476/188613916-f009650c-71cc-4c22-a385-e64c4923b57a.png)

2022-09-07 05:01 UTC, Romakita requested changes

2022-09-07 05:01 UTC, Romakita commented on docs/tutorials/objection.md
> +// (e.g.: `movie.ownerId` and `user.id`)
This comment may be a potential error in a json fragment code. 

You can use a block tip after code example:

```
::: tip

my tip

:::
```

2022-09-07 05:37 UTC, Romakita requested changes

2022-09-07 05:37 UTC, Romakita commented on packages/orm/objection/src/decorators/hasMany.spec.ts
> +      @HasMany({modelClass: Pet})
I prefer that because the type is mandatory:
```typescript
@HasMany(Pet) // without circular ref
@HasMany(() => Pet) // for circular ref
pets?: Pet[];
```

But you can use CollectionOf to set the type correctly.
Because, to be used correctly with the json-mapper, CollectionOf will be mandatory.

So the `HasMany` must call the `CollectionOf` decorator to simplify the model declaration

```typescript
@CollectionOf(Pet)
pets?: Pet[];
```

@tsed/core provide a way to combine decorators:

```typescript
export function HasMany(type: Type<any> | () => Type<Any>, opts: PluralRelationshipOptsWithThrough): {
    return useDecorators(
     RelatesTo(Model.HasManyRelation, {...opts, type}), 
    CollectionOf(type)
   )
}
```

Also, keep in mind, the possibility to support the circular ref. So the decorator should support this implementation:

```typescript
@CollectionOf(() => Pet) // it's already supported by CollectionOf
pets?: Pet[];
```

Potential circular ref, that we need to support:

```typescript
class User {
  role: Role
}

class Role {
   users: User[]
}
```

2022-09-07 05:37 UTC, Romakita commented on packages/orm/objection/src/decorators/manyToMany.spec.ts
>        @ManyToMany({
Idem.

```typescript
@ManyToMany(Pet)
@ManyToMany(() => Pet)

@ManyToMany(Pet, {...})
@ManyToMany(() => Pet, {...})
```

2022-09-07 05:37 UTC, Romakita commented on packages/orm/objection/src/decorators/relatesTo.ts
>    return useDecorators(
ho ok. You already implemented the collectionOf :) nice.

You can simplify you code. The useDecorators filters decorators when the value is falsy ;):

```typescript
return useDecorators(
    opts?.type ? CollectionOf(opts.type) : Property(),
    StoreFn((store, params) => {
      if (isFunction(opts?.type)) {
         opts.type = opts.type()  // resolve the circular ref
      } 
      store.set(OBJECTION_RELATIONSHIP_KEY, createRelationshipMapping(params, relation, opts));
    })
    
 ```   
 Note: I prefer `type` rather than `modelClass` because, type is already used by the @tsed/core @tsed/schema to define the property type.

2022-09-07 05:37 UTC, Romakita commented on packages/orm/objection/src/domain/RelationshipOpts.ts
> +  Omit<RelationMapping<any>, "relation" | "join" | "modelClass"> & {modelClass: Type<any>};
modelClass to type

2022-09-07 05:37 UTC, Romakita commented on packages/orm/objection/src/utils/createJoinKeys.ts
> +        through: (opts && "through" in opts && opts.through) || {
why have you changed this line ?

2022-09-07 05:37 UTC, Romakita commented on packages/orm/objection/src/utils/createJoinKeys.ts
> +        through: (opts && "through" in opts && opts.through) || {
for me `opts?.through` is equivalent to `opts && "through" in opts && opts.through`

2022-09-07 05:37 UTC, Romakita commented on packages/orm/objection/src/utils/createJoinKeys.ts
> +  const FOREIGN_MODEL = (opts && "modelClass" in opts && opts.modelClass) || Metadata.getType(target, propertyKey);
opts?.type || Metadata.getType(target, propertyKey)

2022-09-07 05:37 UTC, Romakita commented on packages/orm/objection/src/utils/createJoinKeys.ts
> +  const FOREIGN_MODEL = (opts && "modelClass" in opts && opts.modelClass) || Metadata.getType(target, propertyKey);
hum the usage of targetClass and target in the same function is confusing ^^.

```typescript
createJoinKeys(targetClass: any, foreignClass: any, propertyKey: string, relation: RelationType, opts?: RelationshipOpts) {
```

2022-09-07 05:39 UTC, Romakita commented
@rossyman Great job ;)

Just small cosmetics changes !

See you
Romain

2022-09-07 23:15 UTC, rossyman commented on packages/orm/objection/src/utils/createJoinKeys.ts
> +        through: (opts && "through" in opts && opts.through) || {
Since `RelationshipOpts` is now a union, we need to discriminate on that otherwise TypeScript will always think `through` does not exist. Adding in a type-guard here instead to make it a bit easier to read.

2022-09-07 23:26 UTC, rossyman commented on packages/orm/objection/src/decorators/relatesTo.ts
>    return useDecorators(
Luckily objection can also resolve circular references in the same way out of the box, so there's no need to re-assign the value of `type` to the called function as Objection will do that for us 😄

2022-09-07 23:41 UTC, rossyman commented on packages/orm/objection/src/decorators/relatesTo.ts
>    return useDecorators(
Adding in an extra check here to ensure `.prototype` isn't in `opts?.type`, as `isFunction` returns true for both Constructable and Callable types (So this code would execute on both the Model and factory function)

2022-09-07 23:45 UTC, rossyman commented on packages/orm/objection/src/utils/createJoinKeys.ts
> +  const FOREIGN_MODEL = (opts && "modelClass" in opts && opts.modelClass) || Metadata.getType(target, propertyKey);
So the `propertyKey` metadata is installed on the `Model` class, so that's why we need to differentiate across `targetClass` and `target` -- `tableName` is on the `targetClass` instead of `target` since it's defined through a class decorator.

2022-09-07 23:45 UTC, rossyman commented on packages/orm/objection/src/utils/createJoinKeys.ts
> +  const FOREIGN_MODEL = (opts && "modelClass" in opts && opts.modelClass) || Metadata.getType(target, propertyKey);
Renamed to `targetClass` and `targetSuper`, hopefully a bit easier to understand now.

2022-09-07 23:46 UTC, rossyman commented
Good to go! 🚀 

![Screenshot 2022-09-08 at 00 42 17](https://user-images.githubusercontent.com/10212476/189001965-df82c238-ccd3-4bb4-b395-f8f664003d4e.png)

2022-09-07 23:51 UTC, rossyman commented
Just on a side note, `Objection.js` isn't listed under the Plugins sidebar section on the docs site.

2022-09-08 05:34 UTC, Romakita commented
@rossyman Perfect PR ;)

Ready to merge for me!

2022-09-08 05:34 UTC, Romakita approved these changes

2022-09-08 07:55 UTC, merged

2022-09-08 08:58 UTC, Romakita commented
:tada: This PR is included in version 6.131.0 :tada:

The release is available on:
- `v6.131.0`
- [GitHub release](https://github.com/tsedio/tsed/releases/tag/v6.131.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-09-16 16:57 UTC, Romakita commented
:tada: This PR is included in version 7.0.0-rc.6 :tada:

The release is available on:
- `v7.0.0-rc.6`
- [GitHub release](https://github.com/tsedio/tsed/releases/tag/v7.0.0-rc.6)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: