feat(add ajv-errors support): add foundation
TypedProject/ts-express-decorators pull request #2183
Opened 2022-12-03 14:41 UTC by Crunchyman-ralph

- Add defaultMsg, errorMsg
- add withErrorMsg wrapper

## Information

| Type                  | Breaking change |
| --------------------- | --------------- |
| Feature/Fix/Doc/Chore | Yes/No          |

---

## Todos

- [ ] Tests
- [ ] Coverage
- [ ] Example
- [ ] Documentation

2022-12-05 07:36 UTC, Romakita approved these changes

2022-12-05 07:36 UTC, Romakita commented
@Crunchyman-ralph  Perfect ;)

2022-12-13 10:40 UTC, Crunchyman-ralph commented
> * [x]  Decorators works on class and properties
> * [ ]  Decorators are correctly exported:
>   
>   * [x]  ErrorMsg
>   * [ ]  TypeError
>   * [x]  RequiredError
>   * [x]  DefaultError
> * [x]  Ajv is correctly configured with ajv-errors (Edit https://github.com/TypedProject/tsed/blob/production/packages/ajv/src/services/Ajv.ts#L48)
> * [ ]  Documentation is up-to-date (model.md and ajv.md)
> * [ ]  Unit test cover correctly the decorators.
> * [ ]  Integration test cover the success and error cases.

I still have a question about what a typeError represents, is it related to decorators like @Integer() ? 

I will do the documentation once we have finished everything to not have to modify it everytime we change something during the review.

Unit tests could have better coverage.

2022-12-13 13:03 UTC, Romakita commented
@Crunchyman-ralph TypeError is a simple shortcut decorator which can be used on class, to customize the error message related to `type` field on json schema ;)

```typescript
@TypeError("should be an object") // shortcut to ErrorMsg({type: 'msg'})
class MyClass {}
```

See you :)

2022-12-16 16:06 UTC, Crunchyman-ralph commented
> > * [ ]   Documentation is up-to-date (model.md and ajv.md)
> > * [ ]   Integration test cover the success and error cases.
> 

Thanks for the support on this PR romain, I have added the TypeError decorator and noticed how you could using @ErrorMsg with this format (@ErrorMsg({foo:bar}) instead of @ErrorMsg("foo", bar))

So I just decided to change the way the function works, also did a few more fixes.

All that I have left is the documentation and the integration tests.

For the documentation:
- where would you put this part of the documentation in the model.md file and the ajv.md file (since we noticed that these changes were specific to spec and not necessarily to ajv, I thought maybe it should only go in model.md ?

For the integration tests:
- Where would they go ? Do you have any good examples of any other integration tests by any chance ?

2022-12-16 16:52 UTC, Romakita commented
> For the documentation:
> where would you put this part of the documentation in the model.md file and the ajv.md file (since we noticed that these changes were specific to spec and not necessarily to ajv, I thought maybe it should only go in model.md ?
 
We can update the model.md b adding a new section :) (ajv is always included in a Ts.ED app)   

> For the integration tests:
> Where would they go ? Do you have any good examples of any other integration tests by any chance ?
Yes, you have two places for that.

1) If you want to run integration over all platform (Express, Koa), this is the good place:
https://github.com/tsedio/tsed/tree/production/packages/platform/platform-test-utils/src/tests

You have to run `yarn test:integration` - (run it directly from IDE isn't possible).

2) If you code isn't really related to a specific platform, you can add the integration test here:

2023-01-11 23:56 UTC, Crunchyman-ralph commented
@Romakita I have finally gotten around to getting the end to end tests as well as the documentation down.

It's a shame the documentation doesn't have a search feature, would make things much easier.

Other than that the PR is ready for review and eventually a merge.

It has been a pleasure contributing to this project, I learned a lot (especially with unit tests and e2e tests)

2023-01-15 07:51 UTC, Romakita commented
Hello @Crunchyman-ralph 
<img width="508" alt="Capture d’écran 2023-01-15 à 08 50 38" src="https://user-images.githubusercontent.com/1763311/212529118-3cb2c781-17dc-4a4e-94fa-b2960983a780.png">

The documentation have search feature on the website:
 <img width="508" alt="Capture d’écran 2023-01-15 à 08 50 38" src="https://user-images.githubusercontent.com/1763311/212529118-3cb2c781-17dc-4a4e-94fa-b2960983a780.png">
 
it use algolia :D 

Thanks again for the PR! awesome!

2023-01-15 07:54 UTC, Romakita requested changes

2023-01-15 07:54 UTC, Romakita commented on packages/specs/ajv/package.json
> +    "ajv-errors": "3.0.0"
you can set ajv-errors as dependencies like ajv-format

2023-01-15 08:00 UTC, Romakita commented
OK just a minor change around the package.json

We will merge the PR. The next step (next PR) will be to wrap all decorators that produce an error message (like Required decorator).
We can wrap the following decorators:

- [ ] MinLength/MaxLength
- [ ] Min/Max/ExclusiveMin/ExclusiveMax
- [ ] MinItems/MaxItems
- [ ] MinProperties/MaxProperties
- [ ] UniqItems
- [ ] Format
- [ ] Integer
- [ ] MultipleOf
- [ ] Pattern
- [ ] Enum ?

It should be easy, now that the mechanism is implemented :D

2023-01-15 13:53 UTC, Romakita approved these changes

2023-01-15 17:14 UTC, Romakita commented
/rebase

2023-01-15 17:59 UTC, merged

2023-01-15 18:29 UTC, Romakita commented
:tada: This PR is included in version 7.11.0 :tada:

The release is available on:
- `v7.11.0`
- [GitHub release](https://github.com/tsedio/tsed/releases/tag/v7.11.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: