feat(temporal): add new module for asynchronous workflows with temporal.io
TypedProject/ts-express-decorators pull request #2464
Opened 2023-10-03 10:15 UTC by ochrstn

## Information

Add a new module for asynchronous workflows with [temporal.io](https://temporal.io)

Type | Breaking change
---|---
Feature | no 🙏 

## Usage example

for detailed explanation see also readme/tutorial

1. Decorate classes and methods:

```typescript
import {Temporal, Activity} from "@tsed/temporal";

@Temporal()
export class UserOnboardingActivities {
  constructor(private userService: UserService, private emailService: EmailService) {}

  @Activity()
  async sendVerificationEmail(email: string) {
    return this.emailService.sendVerificationEmail(email);
  }

  @Activity()
  async activateUser(email: string) {
    return this.userService.activateUser(email);
  }

  @Activity()
  async sendWelcomeEmail(email: string) {
    return this.emailService.sendWelcomeEmail(email);
  }

  @Activity()
  async sendFollowUpEmail(email: string) {
    return this.emailService.sendFollowUpEmail(email);
  }

  @Activity()
  async deleteUser(email: string) {
    return this.userService.deleteUser(email);
  }
}
```

2. Write a workflow:

```ts
import {proxyActivities, defineSignal, setHandler, condition, sleep} from "@temporalio/workflow";
import {Activities} from "../activities";

export const isVerifiedSignal = defineSignal("verificationSignal");

export async function onboardUser(email: string): Promise<string> {
  const {sendVerificationEmail, activateUser, sendWelcomeEmail, sendFollowUpEmail, deleteUser} = proxyActivities<Activities>({
    startToCloseTimeout: "1 minute"
  });

  let isVerified = false;
  setHandler(isVerifiedSignal, () => {
    isVerified = true;
  });

  // 1. Send verification email
  await sendVerificationEmail(email);

  // 2. Wait for verification ...
  const verifiedInTime = await condition(() => isVerified, "1w" /* or for a timeout */);
  if (!verifiedInTime) {
    // 3a. If not verified in time, delete user
    await deleteUserAndTenant(email);
    return false;
  }

  // 3b. If verified in time, send welcome email
  await sendWelcomeEmail(email);

  // 4. Send follow up email after one day
  await sleep("1d"); // special sleep function by temporal
  await sendFollowUpEmail(email);
}
```

3. Inject client:

```typescript
import {Service, AfterRoutesInit} from "@tsed/common";
import {TemporalClient} from "@tsed/temporal";
import {onboardUser} from "../workflows";

@Service()
export class UsersService implements AfterRoutesInit {
  @Inject()
  private temporalClient: TemporalClient;

  async create(user: User): Promise<User> {
    // ...
    await this.temporalClient.workflow.start(onboardUser, {
      args: [user.email],
      taskQueue: "onboarding",
      workflowId: `onboarding-${user.id}`
    });
  }
}
```

4. Start a worker:

```ts
import {bootstrapWorker} from "@tsed/temporal";
import {Server} from "./app/Server";

const worker = await bootstrapWorker(Server, {
  worker: {
    taskQueue: "onboarding",
    workflowsPath: require.resolve("./temporal") // other example: path.join(process.cwd(), 'dist/apps/api/temporal/index.ts');
  },
  connection: {
    /* optional: see NativeConnectionOptions of @temporalio/worker */
  },
  platform: {
    /* optional: see PlatformBuilderSettings of @tsed/common */
    componentsScan: false,
    logger: {
      level: "info"
    }
  }
});
await worker.run();
```

## Todos

- [x] Tests
- [x] Coverage 🆘 
- [x] Example
- [x] Documentation

2023-10-04 08:06 UTC, Romakita commented
Hello @ochrstn 
Thanks for the PR ^^
For the coverage don't be afraid. Since the repo use `@swc/jest` the coverage isn't exact on the branch. It's bug from this package and actually isn't resolved, so just update the coverage branch in the jest.config.js to solve your issue.

See you
Romain

2023-10-04 08:42 UTC, Romakita requested changes

2023-10-04 08:42 UTC, Romakita commented on packages/third-parties/temporal/src/TemporalModule.ts
> +  async $onDestroy(): Promise<any> {
Can be moved to the factory directly

2023-10-04 08:42 UTC, Romakita commented on packages/third-parties/temporal/src/services/TemporalFactory.ts
> +});
```ts
registerProvider({
  provide: TemporalClient,
  deps: [Configuration, TemporalConnection],
  useFactory(settings: Configuration, connection: TemporalConnection) {
    const {temporal} = settings;
    if (!temporal?.enabled) {
      return null;
    }

    const client = new TemporalClient({
      connection,
      ...temporal.client
    });

    return client;
  }, 
  {
     hooks: {
       $onDestroy: async (client: Client | null)  => {
         return client && this.client.connection.close();
       }
     }
  }
});
```

2023-10-04 08:42 UTC, Romakita commented on packages/third-parties/temporal/src/TemporalModule.ts
> +
```ts
constructor(@Inject(PROVIDER_TYPE_TEMPORAL) temporalServices: any[]  // replace any by interface ?
```

2023-10-04 08:42 UTC, Romakita commented on packages/third-parties/temporal/src/TemporalModule.ts
> +  protected getProviders(): Provider<any>[] {
can be removed

2023-10-04 08:42 UTC, Romakita commented on packages/third-parties/temporal/src/TemporalModule.ts
> +    return this.getProviders().reduce((activities, provider) => Object.assign(activities, this.getActivitiesFromProvider(provider)), {});
```ts
    return this.temporalServices.reduce((activities, instance) => Object.assign(activities, this.getActivitiesFromProvider(instance)), {});
```

2023-10-04 08:42 UTC, Romakita commented on packages/third-parties/temporal/src/TemporalModule.ts
> +    const activities = {};
```ts
protected getActivitiesFromProvider(instance: any) { // 
    const provider = this.injector.getProvide(classOf(instance))
    const store = provider.store.get<TemporalStore>(TEMPORAL_STORE_KEY, {});

    return Object.entries(store.activities || {}).reduce((activities, [propertyKey, {name}]) => {
      const jobProcessor = instance[propertyKey].bind(instance);
      const jobName = name || propertyKey;
      
      return {
         ...activities,
         [jobName]: jobProcessor
      }
    }, {});
}
```

2023-10-04 08:42 UTC, Romakita commented on packages/third-parties/temporal/src/services/TemporalFactory.ts
> +  deps: [Configuration],
```ts
registerProvider({
  provide: TemporalConnection,
  deps: [Configuration, Logger],
  async useAsyncFactory(settings: Configuration, logger: Logger) {
    const {temporal} = settings;
    
    if (!temporal?.enabled) {
      return null;
    }

    try {
      logger.info("Connecting to Temporal Server: ", temporal.connection?.address || "default");
      const connection = await Connection.connect(temporal.connection);
      logger.info("... connected to Temporal Server: ", temporal.connection?.address || "default");
      return connection;
    } catch (error) {
      logger.error("Failed to connect to Temporal Server:", error);
      throw error;
    }
  }
});
```

2023-10-04 08:43 UTC, Romakita commented
@ochrstn  Just small changes but great PR :)

2023-10-04 08:45 UTC, Romakita requested changes

2023-10-04 08:45 UTC, Romakita commented on docs/.vuepress/config.base.js
> +                text: "Temporal",
you can add also Temporal on the sidebar section in the configuration.

On the docs/README.md you can edit the home page and add icon to highlight your new module:

 
<img width="1086" alt="Capture d’écran 2023-10-04 à 10 44 18" src="https://github.com/tsedio/tsed/assets/1763311/f9e7ca19-69cd-41c7-aa4c-a2a3ff5cacc6">

Edit this file here: https://github.com/tsedio/tsed/blob/production/docs/readme.md?plain=1#L178

2023-10-04 09:49 UTC, ochrstn commented on packages/third-parties/temporal/src/TemporalModule.ts
> +
I can't get `constructor(@Inject(TEMPORAL_STORE_KEY) private temporalServices: any[]) {}` to work. It results in an empty array.

2023-10-04 09:51 UTC, ochrstn commented
The temporal testing package downloads some stuff to start a local server. Thats why the test probably has a timeout: 
https://github.com/tsedio/tsed/actions/runs/6391803694/job/17347786663?pr=2464#step:6:84

how to deal with that?

2023-10-04 10:01 UTC, Romakita commented on packages/third-parties/temporal/src/TemporalModule.ts
> +
Yes because you use: constructor(@Inject(TEMPORAL_STORE_KEY) private temporalServices: any[]) {}

and not PROVIDER_TYPE_TEMPORAL

2023-10-04 10:43 UTC, Romakita commented
Maybe you can add command line before test to install dependencies ?

2023-10-05 06:35 UTC, Romakita commented
@ochrstn I'll take time to help you on the integration test issue ;)
Finish your changes on the PR and I'll take the next step!

2023-10-05 06:38 UTC, ochrstn commented
> @ochrstn I'll take time to help you on the integration test issue ;) Finish your changes on the PR and I'll take the next step!

Oh thanks, but I just pushed something 😅

2023-10-05 06:50 UTC, ochrstn commented
> > @ochrstn I'll take time to help you on the integration test issue ;) Finish your changes on the PR and I'll take the next step!
> 
> Oh thanks, but I just pushed something 😅

ok, that didn't helped much  🥲

All other changes to the PR are already done, or am I missing something?

2023-10-05 09:27 UTC, Romakita commented
> All other changes to the PR are already done, or am I missing something? 

I'll check the PR ;)

2023-10-05 09:28 UTC, Romakita commented
You've right all changes are done ! Thanks :)

2023-10-13 06:50 UTC, Romakita commented
Hello @ochrstn 
Sorry for the delay but finally fixed :D. I just added timeout option on afterAll, beforeAll (replaced all *Each by *All).

If it's ok for you. Go to merge :D ?
See you
Romain

2023-10-13 09:01 UTC, ochrstn commented
> Hello @ochrstn Sorry for the delay but finally fixed :D. I just added timeout option on afterAll, beforeAll (replaced all *Each by *All).
> 
> If it's ok for you. Go to merge :D ? See you Romain

Looks good to me. Thanks for your time on the pull request. Feel free to merge it 🚀

2023-10-13 10:38 UTC, Romakita approved these changes

2023-10-13 10:38 UTC, merged

2023-10-13 11:09 UTC, Romakita commented
:tada: This PR is included in version 7.37.0 :tada:

The release is available on:
- `v7.37.0`
- [GitHub release](https://github.com/tsedio/tsed/releases/tag/v7.37.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: