feat(bullmq): add new bullmq integration for
TypedProject/ts-express-decorators pull request #2472
Opened 2023-10-11 06:11 UTC by abenerd

## Information

| Type                  | Breaking change |
| --------------------- | --------------- |
| Feature | No          |

---

New [BullMQ](https://bullmq.io) integration for Ts.ED to easily create and dispatch jobs. 

## Usage example

```typescript
import {AsJob, Job} from "@tsed/bullmq";

@AsJob("example")
class ExampleJob implements Job {
  public handle(payload: {msg: string}) {
    console.info("New message incoming", payload.msg);
  }
}
```

```ts
import {Service} from "@tsed/di";
import {JobDispatcher} from "@tsed/bullmq";
import {ExampleJob} from "./jobs/ExampleJob";

@Service()
class MyService {
  constructor(private readonly dispatcher: JobDispatcher) {}

  public async doingSomething() {
    await this.dispatcher.dispatch(ExampleJob, {msg: "this message is part of the payload for the job"});

    console.info("I just dispatched a job!");
  }
}
```

## Todos

- [X] Tests
- [X] Coverage
- [X] Example
- [X] Documentation

2023-10-13 06:44 UTC, Romakita requested changes

2023-10-13 06:44 UTC, Romakita commented on docs/tutorials/bullmq.md
> +The [BullMQ](https://bullmq.io) Module for Ts.ED allows you to decorate a class using the `@AsJob` decorator and implement the `Job` interface provided by the module.
Can you rename AsJob by Job and the Job interface by JobMethods. I already had this problems and by convention I add Methods on interface, to keep the decorator name simple ;)

2023-10-13 06:44 UTC, Romakita commented on packages/third-parties/bullmq/src/BullMQModule.ts
> +  $beforeInit() {
There is reason to use $beforeInit instead $onInit ?

2023-10-13 06:44 UTC, Romakita commented on packages/third-parties/bullmq/src/BullMQModule.ts
> +    this.injector.getMany<Job>("bullmq:cron").map((job) => this.dispatcher.dispatch(getComputedType(job)));
good job :D. Now you are a @tsed/di expert !

2023-10-13 06:44 UTC, Romakita commented on packages/third-parties/bullmq/src/decorators/AsJob.ts
> +    Injectable({
it's probably an error!! I don't understand why you need to declare the injectable provider twice. You'll have two instance in the same container.

Also, you use a class. Give the provide props to Injectable isn't necessary.

2023-10-13 06:44 UTC, Romakita commented on packages/third-parties/bullmq/src/decorators/AsJob.ts
> +    Injectable({
```ts
Injectable({
  type: opts.repeat ? "bullmq:cron" : "bullmq:job"
})
```

2023-10-13 06:44 UTC, Romakita commented on packages/third-parties/bullmq/src/decorators/AsJob.ts
> +export type JobStore = {
export this type in new interfaces directory to reuse in JobFactory

2023-10-13 06:44 UTC, Romakita commented on packages/third-parties/bullmq/src/processors/ProcessorFactory.ts
> +      const j = this.injector.get<Job>(`bullmq.job.${job.name}`);
Here is the right way to retrieve job based on metadata (and to avoid twice injectable provider in container)

```typescript
const job = this.injector
   .getMany<Job>("bullmq:cron")
   .find(instance => 
      Store.from(classOf(instance)).get<JobStore>("bullmq").name === job.name)

if (!job) {
  throw new Error ('Job instance not found')
}



```

2023-10-13 06:46 UTC, Romakita commented
Hello @abenerd 
Thanks for this great PR. just small changes ;)

Tell me when it's done!
See you
Romain

2023-10-13 07:14 UTC, abenerd commented on packages/third-parties/bullmq/src/BullMQModule.ts
> +  $beforeInit() {
My thought process was that I wanted this to be ready for when the caller wanted to interact with the queues and workers themselves.

2023-10-13 07:16 UTC, abenerd commented on packages/third-parties/bullmq/src/processors/ProcessorFactory.ts
> +      const j = this.injector.get<Job>(`bullmq.job.${job.name}`);
I'm not sure how this would be better, as I would potentially be retrieving dozens of services from the container while I only need one and know exactly the name to retrieve it by. I also removed the double injectable so this should not be a problem anymore.

2023-10-13 09:53 UTC, Romakita commented on packages/third-parties/bullmq/src/processors/ProcessorFactory.ts
> +      const j = this.injector.get<Job>(`bullmq.job.${job.name}`);
I understand, but create multiple instance of the same class in the container isn't the good way. And getMany isn't a method to create injectable provider. is just a method to get all instance of the same type.
Using injector.get is maybe simple but in fact the cost time execution is nearly the same as `getMany` + `filter()`.

But you can add service to resolve that or add a method in your module:

```ts
@Module()
export class BullMQModule implements BeforeInit {
  getJob(name: string) {
     return this.injector
   .getMany<Job>("bullmq:cron")
   .find(instance => 
      Store.from(classOf(instance)).get<JobStore>("bullmq").name === job.name)
  }
}

// alternative

@Module()
export class BullMQModule implements BeforeInit {
   #cronJobs: Map<string, Job>;

   constructor(injector: InjectorService, @Inject("bullmq:cron") cronJobs: Job[]) {
      this.#cronJob = toMap(cronJobs, (instance) => Store.from(classOf(instance)).get<JobStore>("bullmq").name)
   }

  getJob(name: string) {
     return this.#cronJob.get(name)
  }
}

// usage
 const j = this.injector.get<BullMQModule>(BullMQModule).getJob(name);
```

2023-10-13 10:17 UTC, abenerd commented on packages/third-parties/bullmq/src/processors/ProcessorFactory.ts
> +      const j = this.injector.get<Job>(`bullmq.job.${job.name}`);
Ah yeah I can see that, thank you for the clarification!

2023-10-16 05:58 UTC, abenerd commented
BullMQ uses Redis for storage and I'm having problems mocking it in the tests, I don't really want to add it to the CI when I'm the only one using it, would you be able to help me out here @Romakita?

2023-10-16 07:33 UTC, Romakita approved these changes

2023-10-16 07:43 UTC, Romakita commented
@abenerd I fixed your tests and I remove the unnecessary factory to keep the logic in the module directly. Also I added the runInContext from @tsed/di to allow the context injection in a Service.

On point that maybe need to be improved is the Job decorator. His name is similar to Job from bullmq, and it'll probably cause conflict if the consumer (worker) need to get the job as second parameter of the handler (e.g.: add added it as second handler parameters in the PR).

Maybe renaming the decorator is necessary. Proposals: JobService or JobController ? 
 
 See you
 Romain

2023-10-16 08:46 UTC, Romakita approved these changes

2023-10-16 08:46 UTC, abenerd commented
Thank you so much for that @Romakita! And yeah I can see how this could be confusing, I changed the decorator name to `JobController` to imply that this is not a service that the user should inject themselves.

2023-10-16 13:15 UTC, Romakita commented
Ready ? @abenerd

2023-10-16 13:23 UTC, abenerd commented
Yeah, ready to go @Romakita!

2023-10-16 15:20 UTC, merged

2023-10-16 15:52 UTC, Romakita commented
:tada: This PR is included in version 7.38.0 :tada:

The release is available on:
- `v7.38.0`
- [GitHub release](https://github.com/tsedio/tsed/releases/tag/v7.38.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: