feat(bullmq): extend configuration
TypedProject/ts-express-decorators pull request #2536
Opened 2023-11-17 12:43 UTC by EinfachHans

## Information

| Type                  | Breaking change |
| --------------------- | --------------- |
| Feature|No          |

---

closes #2534 

### What changed?

- Removed `disableWorker` (this option was unused, i would not say it is a breaking change 🤔)
- Deprecated `defaultJobOptions`
- Added `defaultJobOptions`, `queueOptions`, `defaultWorkerOptions` & `workerOptions`
- Deep merge the configuration of queues and workers by the connection, default options and specific options
- Improved typing
- Updated docs

<hr>

I don't know how i can test the option merge correctly 🤔 If needed please guide me on how to get the call args there.

2023-11-17 12:48 UTC, EinfachHans commented
Looks like i'm not allowed to add reviewers 🤔 So i do it cheeky in this comment:

- @Romakita 
- @abenerd

2023-11-17 17:19 UTC, abenerd requested changes
Can you also add some test for the config merging, both for the queues and workers, otherwise that looks great thanks!

2023-11-17 17:19 UTC, abenerd commented on packages/third-parties/bullmq/src/contracts/JobMethods.ts
> +export interface JobMethods<DataType = any, ReturnType = unknown> {
```suggestion
export interface JobMethods<DataType = unknown, ReturnType = unknown> {
```

I think we should use `unknown` here too.

2023-11-17 17:19 UTC, abenerd commented on packages/third-parties/bullmq/src/config/config.ts
> +   * @deprecated Use defaultQueueOptions instead. Will be removed in the next major release
I like the deprecation, that is great!

2023-11-17 17:19 UTC, abenerd commented on packages/third-parties/bullmq/src/config/config.ts
> +import {type ConnectionOptions, type DefaultJobOptions, QueueOptions, WorkerOptions} from "bullmq";
```suggestion
import {type ConnectionOptions, type DefaultJobOptions, type QueueOptions, type WorkerOptions} from "bullmq";
```

Best make this also type imports I think.

2023-11-17 17:32 UTC, EinfachHans commented
@abenerd comments addressed, but i'm not clear how to test the merge of the configurations there 🤔

Any idea?

2023-11-17 17:39 UTC, abenerd commented
Currently not on my computer anymore, and probably not until Monday so I can't try out stuff myself but maybe try also mocking the `InjectorService` to later verify that it has been called with the correct arguments. We also do something similar in the `BullMQModule.spec.ts`.

2023-11-17 17:41 UTC, EinfachHans commented
yeah i tried it, but that seems to not work. I'm unsure, but i think you can't mock the `InjectorService` for `PlatformTest.create` like this. I think the test in `BullMQModule.spec.ts` only works because it tests to not have been called.

Am i right @Romakita ?

2023-11-18 08:36 UTC, Romakita commented
No you don't need to mock injectorService to test the merge configuration. just mock `new Queue` using jest.

It's already the case:

```ts
jest.mock("bullmq", () => {
  return {
    Queue: class {
      public name: string;

      constructor(name: string) {
        this.name = name;
      }
      close() {}
    },
    Worker: class {
      public name: string;

      constructor(name: string) {
        this.name = name;
      }
      close() {}
    }
  };
});
```

Then use PlatformTest.create({bullmq}) to check you different scenario (using different describe).
```ts
import { PlatformTest } from "@tsed/common";
import { instance, mock, when } from "ts-mockito";
import {
  JobDispatcher
} from "../../../../../../../Volumes/workspaces/tsed/ts-express-decorators/packages/third-parties/bullmq/src/index";

describe("module", () => {

  describe("When configuration is given from default server options", () => {
    let dispatcher: JobDispatcher;
    beforeEach(async () => {
      dispatcher = mock(JobDispatcher);
      when(dispatcher.dispatch(CustomCronJob)).thenResolve();

      await PlatformTest.create({
        bullmq: {
          // add default options
        },
        imports: [
          {
            token: JobDispatcher,
            use: instance(dispatcher)
          }
        ]
      });
    });
    beforeEach(() => {
    });
    afterEach(PlatformTest.reset);

    /// it
  });

  describe("When configuration is given from default server options and decorators", () => {
    let dispatcher: JobDispatcher;
    beforeEach(async () => {
      dispatcher = mock(JobDispatcher);
      when(dispatcher.dispatch(CustomCronJob)).thenResolve();

      await PlatformTest.create({
        bullmq: {
          // add default options
        },
        imports: [
          {
            token: JobDispatcher,
            use: instance(dispatcher)
          }
        ]
      });
    });
    beforeEach(() => {
    });
    afterEach(PlatformTest.reset);

    /// it
  });
});

```

2023-11-18 13:17 UTC, EinfachHans commented
Test added 👍🏼

2023-11-20 06:12 UTC, abenerd commented
You know, now that I've slept on in a bit I don't think we should deprecate the `disableWorker` property, it is more explicit and more easily configurable. Configurations are probably read from the environment and if you enable disabling the worker via the `workerQueues` property you have to differentiate between empty values that indicate falling back to using all defined queues and empty values indicating the workers should be disabled. So while it might be a breaking change it would just implement the actual expected behaviour, I think it might be worth it. What do you think @EinfachHans and @Romakita.

2023-11-20 07:17 UTC, EinfachHans commented
Mhh i think `disableWorkers` is not very usefull. Why would you have no worker. But even if you want to, you could still do `workerQueues: []`, couldn't you?

2023-11-20 07:32 UTC, abenerd commented
We want to decouple the queue from the rest of our api so we can independently scale the two and should there be a catastrophic failure on the worker it would not tear down the api as well. 
That is also the reason you can specify worker queues instead of always processing jobs from all queues so you can work jobs on certain queues on machines with more RAM or CPU for example.

2023-11-20 07:34 UTC, EinfachHans commented
Okay and what should `disableWorkers` do? At the end of the day the same as `workerQueues: []` right? Then i would leave it like this and maybe document that somewhere

2023-11-20 07:40 UTC, abenerd commented
Sure, but when you read the config from the environment you have to add extra logic to detect whether the `workerQueues` are empty to disable the worker or empty to work on all queues. And having the property `disableWorker` is also a lot more explicit than just an empty array.

2023-11-20 07:45 UTC, EinfachHans commented
Feels for me like having two options doing the same thing 🤔 But i can add it back

2023-11-20 07:59 UTC, EinfachHans commented
@abenerd done 😊

2023-11-20 08:00 UTC, abenerd commented
Thanks!

2023-11-20 08:42 UTC, abenerd reviewed
Just a few comments on the documentation otherwise this looks good!

2023-11-20 08:42 UTC, abenerd commented on docs/tutorials/bullmq.md
> +    // Defaultly for every queue added in the `queues` parameter
```suggestion
    // When undefined falls back to all queues specified.
```

2023-11-20 08:42 UTC, abenerd commented on packages/third-parties/bullmq/README.md
> +    // Defaultly for every queue added in the `queues` parameter
```suggestion
    // When undefined falls back to all queues specified.
```

2023-11-20 08:42 UTC, abenerd commented on packages/third-parties/bullmq/src/BullMQModule.ts
> +import {Job, Queue, QueueOptions, Worker, WorkerOptions} from "bullmq";
```suggestion
import {Job, Queue, type QueueOptions, Worker, type WorkerOptions} from "bullmq";
```

I think those could be type imports, we're not actually doing anything with them.

2023-11-20 08:49 UTC, EinfachHans commented
After this is merged i will add a new pull request for #2537 😊

2023-11-20 08:53 UTC, abenerd approved these changes

2023-11-20 12:11 UTC, merged

2023-11-20 12:33 UTC, Romakita commented
:tada: This PR is included in version 7.48.0 :tada:

The release is available on:
- `v7.48.0`
- [GitHub release](https://github.com/tsedio/tsed/releases/tag/v7.48.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: