feat(bullmq): add `FallbackJobController`
TypedProject/ts-express-decorators pull request #2538
Opened 2023-11-20 13:12 UTC by EinfachHans

## Information

| Type                  | Breaking change |
| --------------------- | --------------- |
| Feature | No          |

---

closes #2537 

## What changed ?

- Added a `FallbackJobController` Decorator
- Adjust logic to find a matching job handler:
  1. Search via the job name (as before)
  2. Search a fallback job via the queue name
  3. Search a fallback job without queue name
- Adjusted the Dispatcher to be able to dispatch these kind of jobs (jobs without specific class) as well
- Tests added
- Documentation added
- Add myself as a maintainer

2023-11-20 13:13 UTC, EinfachHans commented
@abenerd ✌🏼

2023-11-20 20:54 UTC, Romakita commented
@EinfachHans can you rebase your branche from production please ;)

2023-11-20 21:06 UTC, EinfachHans commented
@Romakita The branch is up to date with production, can you just "squash and merge" it when it is approved?

2023-11-21 01:34 UTC, Romakita requested changes

2023-11-21 01:34 UTC, Romakita commented on packages/third-parties/bullmq/src/index.ts
> +export * from "./dispatchers/JobDispatcher.options";
JobDispatcherOptions.ts

2023-11-21 06:02 UTC, abenerd commented on packages/third-parties/bullmq/src/dispatchers/JobDispatcher.ts
>      });
Why the change in signature and behavior here? This has nothing to do really with the fallback controller.

Apart from that I also don't really like opening that up to more arbitrary arguments, I think one of the strong suits here is that it is tightly coupled with the declared job controller so that adding invalid jobs or having invalid payloads is harder to achieve. If you want more control over how to dispatch a job you can inject the Queue itself by its name `bullmq.queue.default` / `bullmq.queue.my-awesome-queue`.

2023-11-21 06:02 UTC, abenerd commented on packages/third-parties/bullmq/src/BullMQModule.ts
> +    return this.injector.get<JobMethods>("bullmq.fallback-job");
Does it maybe make sense to retrieve the fallback handler explicitly so we can change how we add the payload, like make the queue, and job name more accessible.

2023-11-21 08:03 UTC, EinfachHans commented on packages/third-parties/bullmq/src/dispatchers/JobDispatcher.ts
>      });
Mhh i like the fact that users would be to dispatch all kind of jobs via the dispatcher service. I also documented that this way of dispatching only makes sense when a fallback controller is defined.

2023-11-21 08:04 UTC, EinfachHans commented on packages/third-parties/bullmq/src/BullMQModule.ts
> +    return this.injector.get<JobMethods>("bullmq.fallback-job");
thought about the same thing, but the job itself is already pushed into the handler and within the job you have the job name and the queue name 🤔

2023-11-21 08:11 UTC, abenerd commented on packages/third-parties/bullmq/src/dispatchers/JobDispatcher.ts
>      });
I think the advantage of the dispatcher is that it integrates so well with the already defined jobs. If you want more control you can reach for the queue from the container, which is already possible. This can, and probably should, be documented better that this is possible and how to do it.
Keeping this out of the dispatcher would also keep it cleaner and easier to maintain.

2023-11-21 08:12 UTC, abenerd commented on packages/third-parties/bullmq/src/BullMQModule.ts
> +    return this.injector.get<JobMethods>("bullmq.fallback-job");
Yeah that is a fair point.

2023-11-21 08:19 UTC, EinfachHans commented on packages/third-parties/bullmq/src/dispatchers/JobDispatcher.ts
>      });
This advantage is not lost, it still works the same as before, it's also extended. What do you say to create a second method for this?

2023-11-21 08:45 UTC, abenerd commented on packages/third-parties/bullmq/src/dispatchers/JobDispatcher.ts
>      });
I'm still not quite sure about this. I also don't really see the use case here actually, you allow users to dispatch jobs that possibly do not exist for control that they already have.

2023-11-21 08:58 UTC, EinfachHans commented on packages/third-parties/bullmq/src/dispatchers/JobDispatcher.ts
>      });
In my case i don't have strict names, they can be dynamic for some reason. That was the reason for the fallback controller in general.

Also i would prefer using the dispatcher instead of injecting the queue directly, to have it same across all jobs 🤔

2023-11-21 09:09 UTC, abenerd commented on packages/third-parties/bullmq/src/dispatchers/JobDispatcher.ts
>      });
Is it not possible to add the dynamic part of the name to the payload? I feel like this is a very special use case that would add a lot of logic to be supported.
Maybe you can write your own dispatcher in your own codebase to dispatch those kinds of jobs, then you would still have a central place where the dispatch logic is handled.

2023-11-21 09:21 UTC, EinfachHans commented on packages/third-parties/bullmq/src/dispatchers/JobDispatcher.ts
>      });
In my case i use the name because bullmq's `getRepetableJobs` doesn't return the payload of each job (for performance reasons), and i need to find a specific repeatable job, for what i use the name - thats the solution i found online.

I dont think that dynamic names are a special use case 🤔

2023-11-21 16:18 UTC, abenerd commented on packages/third-parties/bullmq/src/dispatchers/JobDispatcher.ts
>      });
Yeah fair. But let's still move the logic to another method to keep the methods themselves as simple as possible without having to do all the type juggling. Like a `dispatchHeadlessJob` that accepts the name as a string instead of the job type.

2023-11-22 06:51 UTC, Romakita commented on packages/third-parties/bullmq/src/dispatchers/JobDispatcher.ts
>      });
You can do that to keep the dispatcher implementation simple:

```ts
  public async dispatch(job: string | Type, payload: any, opts?: JobsOptions): Promise<BullMQJob>;
  public async dispatch(jobOptions: JobDispatcherOptions, payload: any): Promise<BullMQJob>;
  public async dispatch(job: Type | JobDispatcherOptions | string, payload: any, opts: JobsOptions = {}): Promise<BullMQJob> {
    const {queueName, name, options} = this.resolveDispatchArgs(job, opts);


    const queue = this.injector.get<Queue>(`bullmq.queue.${queueName}`);

    if (!queue) {
      throw new Error(`Queue(${queueName}) not defined`);
    }

    return queue.add(name, payload, options);
  }

  private resolveDispatchArgs(job: Type | JobDispatcherOptions | string, payload: any, options: JobsOptions = {}) {
    let queueName: string;
    let name: string;
    let defaultJobOptions: JobsOptions | undefined;

    const queue = this.injector.getMany<Queue>("bullmq:queue").find((queue) => queue.name === store.queue);
    if (typeof job === "function") {
      // job is passed as a Type
      const store = Store.from(job).get<JobStore>("bullmq");

      return {
        queueName: store.queue,
        name: store.name,
        options: {
          ...options,
          ...store.options
        }
      }
    }

    if (typeof job === "object") {
      // job is passed as JobDispatcherOptions
      queueName = job.queue;
      name = job.name;

      return {
        queueName: job.queue,
        name: job.name,
        options
      }
    }

    // job is passed as a string
    return {
      queueName: "default",
      name: job,
      options
    }
  }
```

2023-11-22 07:09 UTC, Romakita commented
@EinfachHans For the review and keep commit history clean(in most case), it's preferable to rebase your branch instead of using pull/merge commands. 

Here is the difference:
Pull/merge:
<img width="568" alt="Capture d’écran 2023-11-22 à 08 04 53" src="https://github.com/tsedio/tsed/assets/1763311/08a15c69-d801-4c99-b601-7adce6ce67b1">


Rebase mode: `git rebase origin/production`

<img width="568" alt="Capture d’écran 2023-11-22 à 08 04 32" src="https://github.com/tsedio/tsed/assets/1763311/0956582f-452a-4884-bd3e-851e1abc8e2b">
In this case, you commit is after the latest production tags. It's more clear for me and there is no extra commits :)
and I'm quite reassured to see that, because I know that your dev takes the latest changes into account (even if the pull/merge seems to do it too, that doesn't guarantee me that you haven't made a regression)

I just pushed the branch @EinfachHans (so you need to run `git fetch & git rebase` or reset your local branch to your remote).

See you

2023-11-22 08:03 UTC, EinfachHans commented
@Romakita But what about "Squash & Merge" - wouldn't that in the same?

I normally only use that approach to pull & merge into my feature branches and then squash and merge the branch when merging into the main branch. This produces only one commit and i also can't see any branches in my git visualisation log

2023-11-22 08:48 UTC, Romakita commented
@Romakita But what about "Squash & Merge" - wouldn't that result in the same?

It works. Just in your case, the branch started before the latest version and from another branch. I can be confusing ^^. 
I known there is two point of view between rebase / pull. But my experience on different project has shown me that the rebase is more clear to keep history clean and less error.

2023-11-23 06:44 UTC, abenerd commented on packages/third-parties/bullmq/src/dispatchers/JobDispatcher.ts
> +  }
I was thinking more of a dedicated method to dispatch a job.

2023-11-23 11:00 UTC, EinfachHans commented on packages/third-parties/bullmq/src/dispatchers/JobDispatcher.ts
> +  }
Yeah, that here is what @Romakita suggested and tbh i'm more a fan of that instead of having a second function. By that the implementation is capsuled and more clear

2023-11-24 05:34 UTC, abenerd commented on packages/third-parties/bullmq/src/dispatchers/JobDispatcher.ts
> +  }
Yeah ok, then let's do it that way.

2023-11-24 05:36 UTC, abenerd approved these changes

2023-11-27 12:17 UTC, EinfachHans commented
@Romakita Can you review? 😊

2023-11-27 12:21 UTC, Romakita approved these changes

2023-11-27 12:21 UTC, merged

2023-11-27 12:45 UTC, Romakita commented
:tada: This PR is included in version 7.49.0 :tada:

The release is available on:
- `v7.49.0`
- [GitHub release](https://github.com/tsedio/tsed/releases/tag/v7.49.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: