:star: feat: enable prisma generator support for ESM
TypedProject/ts-express-decorators pull request #2700
Opened 2024-05-08 06:42 UTC by vangie

## Information

| Type                  | Breaking change |
| --------------------- | --------------- |
| Feature/Fix/Doc/Chore | Yes/No          |

---

## Todos

- [ ] Tests
- [ ] Coverage
- [ ] Example
- [ ] Documentation

2024-05-08 07:58 UTC, Romakita requested changes

2024-05-08 07:58 UTC, Romakita commented on packages/orm/prisma/package.json
> +    "build": "rm -rf lib && yarn build:ts && echo '{\"type\":\"module\"}' > lib/esm/package.json",
you don't need that. the build tool generate the correct package.json with the expected type module when you run the yarn build on the root package.json.
Please remove this change ;)

2024-05-08 07:58 UTC, Romakita commented on packages/orm/prisma/src/generator.mts
> +register('extensionless', import.meta.url, {data: {argv1: argv[1]}});
it's preferable to add extension explicitly no ?

2024-05-08 08:00 UTC, Romakita commented
Hello @vangie 
Thanks a lot for this PR. You've missed to commit the yarn.lock file ;)

Also, the repo follow a angular commit convention and use semantic release. Can you remove emoji from your commit message please (isn't supported by semantic release).

The commit message must be:

```
feat(prisma): enable prisma generator support for ESM
```

2024-05-09 02:03 UTC, vangie commented
> Hello @vangie Thanks a lot for this PR. You've missed to commit the yarn.lock file ;)
> 
> Also, the repo follow a angular commit convention and use semantic release. Can you remove emoji from your commit message please (isn't supported by semantic release).
> 
> The commit message must be:
> 
> ```
> feat(prisma): enable prisma generator support for ESM
> ```

OK, I have amended the git msg and add the missing yarn.lock file

2024-05-09 02:09 UTC, vangie commented on packages/orm/prisma/src/generator.mts
> +register('extensionless', import.meta.url, {data: {argv1: argv[1]}});
```
#!/usr/bin/env node --import extensionless/register

import "./cli/generator";
```
The modification above simplifies the originally committed code. However, it requires installing the 'extensionless' module in my own project. I'm not sure how to improve this further. Any suggestions?

2024-05-09 02:35 UTC, vangie commented on packages/orm/prisma/package.json
> +    "build": "rm -rf lib && yarn build:ts && echo '{\"type\":\"module\"}' > lib/esm/package.json",
If I remove the 'lib/esm/package.json' file, it will print the following error when I run `npx prisma generate`
```bash
> npx prisma generate

Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Error: Generator "tsed-prisma-esm" failed:

(node:78280) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/Users/duwan/Workspaces/babelcloud/tsed/packages/orm/prisma/lib/esm/cli/generator.js:1
import { generatorHandler } from "@prisma/generator-helper";
^^^^^^
SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at cjsLoader (node:internal/modules/esm/translators:356:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:305:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
Node.js v20.11.1

 ELIFECYCLE  Command failed with exit code 1.
```

2024-05-09 03:43 UTC, Romakita commented on packages/orm/prisma/package.json
> +    "build": "rm -rf lib && yarn build:ts && echo '{\"type\":\"module\"}' > lib/esm/package.json",
But you don't have to run npx prisma migrate at this step. It's only when the package is published you need that.

Again, if you run yarn build from the root package.json, you see a dist directory. Inside the dist, you will have the tsed prisma package with the generated code (esm/cjs version). 
Also, the build add extension to all imported files in the esm code. You don't need extensionless module.

2024-05-09 03:46 UTC, Romakita commented on packages/orm/prisma/src/generator.mts
> +register('extensionless', import.meta.url, {data: {argv1: argv[1]}});
The target is to generate the code for esm without an additional plugin. So I prefer to not register a loader.

2024-05-09 03:47 UTC, Romakita commented on packages/orm/prisma/src/generator.mts
> +register('extensionless', import.meta.url, {data: {argv1: argv[1]}});
Maybe trying to have the same code base to generate cjs and esm code is an error 🤔

2024-05-09 16:47 UTC, vangie commented on packages/orm/prisma/package.json
> +    "build": "rm -rf lib && yarn build:ts && echo '{\"type\":\"module\"}' > lib/esm/package.json",
I run `npx prisma migrate` in my owner project which generated by tsed.  I have tried top level `yarn build`, many files generated in dist/prisma folder has .js extension in import statement. but it still print following error if I remove the package.json file in lib/esm. 

```
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Error: Generator "tsed-prisma-esm" failed:

(node:71478) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/Users/duwan/Workspaces/babelcloud/tsed/dist/prisma/lib/esm/cli/generator.js:1
import { generatorHandler } from "@prisma/generator-helper";
^^^^^^
SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at cjsLoader (node:internal/modules/esm/translators:356:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:305:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
Node.js v20.11.1
```

2024-05-09 16:53 UTC, vangie commented on packages/orm/prisma/src/generator.mts
> +register('extensionless', import.meta.url, {data: {argv1: argv[1]}});
Using top level yarn build import statement contains .js extension. but js files emit by prisma generator is missing the js extension.

lib/esm/.schema/index.js
```
export * from "./interfaces";
export * from "./models";
export * from "./services/PrismaService";
export * from "./repositories";
```

2024-05-09 16:59 UTC, vangie commented on packages/orm/prisma/src/generator.mts
> +register('extensionless', import.meta.url, {data: {argv1: argv[1]}});
Shall I add a .js suffix to all these import statements? such as following ts file

tsed/packages/orm/prisma/src/generator/utils/generateIndex.ts
```typescript
export function generateIndex(project: Project, baseDirPath: string, hasEnum: boolean) {
  const indexFile = path.resolve(baseDirPath, "index.ts");

  project.createSourceFile(indexFile, undefined, {overwrite: true}).addExportDeclarations(
    [
      {
        moduleSpecifier: "./interfaces"
      },
      hasEnum && {
        moduleSpecifier: "./enums"
      },
      {
        moduleSpecifier: "./models"
      },
      {
        moduleSpecifier: "./services/PrismaService"
      },
      {
        moduleSpecifier: "./repositories"
      }
    ].filter(Boolean) as any[]
  );
}

```

2024-05-21 11:21 UTC, Tomdrouv1 commented
@vangie @Romakita any update for this PR, it would be amazing to add it for the next update, I'm working on a project that I want to turn into full esm support but I can't because of schemas not generated in esm.

Thanks for the work !

2024-05-21 11:34 UTC, Romakita commented
I think publish a code that support commonjs / esm for this plugin is complicated. I started the v8 branch (ESM only). Maybe it's more appropriate to add this PR to the v8 roadmap.

The branch is almost ready. There are small issue related to GQL and prisma module.

Another solution is to duplicate the code inside the tsed/prisma module (one for cjs and one esm) and use exports field to use the appropriate code convention.

See you

2024-05-31 09:02 UTC, Romakita commented
@vangie I pushed some commit to unlock your dev ;)

Now you can generate the code for ESM and CJS.
- I removed extensionless. I prefer to manage extension each time it's necessary in our code.
- I removed the condition to not generate decorator when there is a recursive import, I don't now why you trying to fix that because, you have to generate decorators in any case !

See you

2024-06-01 17:38 UTC, Romakita commented on packages/orm/prisma/src/generator.mts
> +register('extensionless', import.meta.url, {data: {argv1: argv[1]}});
@vangie  done. I fixed all path. You can run locally the appropriate npm scripts "generate:postgres:esm"

If you see something wrong tell me :)

2024-06-01 17:38 UTC, Romakita approved these changes

2024-06-01 17:42 UTC, Romakita commented
@vangie @Tomdrouv1 The PR seems to be ready ;) can you review the changes ?

2024-06-03 13:50 UTC, Tomdrouv1 approved these changes

2024-06-03 13:51 UTC, Tomdrouv1 approved these changes

2024-06-04 05:55 UTC, merged

2024-06-04 06:07 UTC, Romakita commented
:tada: This PR is included in version 7.71.0 :tada:

The release is available on:
- `v7.71.0`
- [GitHub release](https://github.com/tsedio/tsed/releases/tag/v7.71.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-07-01 09:44 UTC, vangie commented
@Romakita 

I have updated TSED to 7.74.1 and regenerate prisma，The following error occurred

```bash
❯ pnpm prisma:generate

> babel-agent@1.0.0 prisma:generate /Users/duwan/Workspaces/babelcloud/babel-agent
> bin/prisma-generate.sh -f

Running prisma generate...
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Error: 
✔ Generated Prisma Client (v5.16.1) to ./node_modules/.pnpm/@prisma+client@5.16.1_prisma@5.16.1/node_modules/@prisma/client in 68ms

ENOENT: no such file or directory, lstat '/Users/duwan/Workspaces/babelcloud/babel-agent/node_modules/.pnpm/@tsed+prisma@7.74.1_@prisma+client@5.16.1_prisma@5.16.1__@tsed+core@7.74.1_@tsed+di@7.74.1_@t_4eo4yxmt2uq5uoc7vp7fbmyr5a/node_modules/@tsed/scripts/backup-index.cjs.js'
```