feat: add `appendChildrenRoutesFirst` configuration option
TypedProject/ts-express-decorators pull request #2711
Opened 2024-05-24 07:25 UTC by EinfachHans

## Information

| Type                  | Breaking change |
| --------------------- | --------------- |
| Feature |No          |

closes #2706

---

## Description

As described in the original issue the children routes should be appended before the controller routes itself. This PR adds a opt-in solution via a configuration setting. As discussed we should follow the following:

- In next major release (`8.0.0`): Set the default of this value to `true` & deprecate the option
- In the next major version after that (`9.0.0`): Remove the option

## Usage example

```typescript
import {Configuration} from "@tsed/di";

@Configuration({
  appendChildrenRoutesFirst: true
})
export class Server {}
```

## Todos

- [X] Tests
- [X] Coverage
- [X] Example
- [X] Documentation

2024-05-24 08:21 UTC, Romakita requested changes

2024-05-24 08:21 UTC, Romakita commented on packages/di/src/common/interfaces/DIConfigurationOptions.ts
> +      /**
this option should not located here because it's base configuration shared with all tsed package.

You have to add option in a new interface in this directory:

https://github.com/tsedio/tsed/blob/fb19f24be64bebaa715d208fd1b30dba9f3c387a/packages/platform/common/src/config/interfaces

Create a file PlatformRouterSettings with the following content: 

```ts
import {JsonMapperGlobalOptions} from "@tsed/json-mapper";

export interface PlatformJsonMapperSettings extends JsonMapperGlobalOptions {}

declare global {
  namespace TsED {
    interface Configuration extends Record<string, any> {
      router?: {
         appendChildrenRoutesFirst?: boolean;
      }
    }
  }
}
```

2024-05-24 08:21 UTC, Romakita commented on packages/di/src/common/interfaces/DIConfigurationOptions.ts
> +      /**
I don't see where you map the appendChildrenRoutesFirst with the router instance ^^?

2024-05-24 08:43 UTC, EinfachHans commented on packages/di/src/common/interfaces/DIConfigurationOptions.ts
> +      /**
@Romakita added the PlatformRouterSettings file. What do you mean with the second question?

2024-05-24 15:31 UTC, Romakita commented on packages/di/src/common/interfaces/DIConfigurationOptions.ts
> +      /**
@EinfachHans Sorry, I forget that the PlatformRouters is an injectable service ^^. forgot my second answer all is fine.

2024-05-24 15:32 UTC, Romakita approved these changes

2024-05-24 15:33 UTC, Romakita requested changes

2024-05-24 15:33 UTC, Romakita commented on packages/platform/common/src/config/interfaces/PlatformRouterSettings.ts
> +export interface PlatformJsonMapperSettings extends JsonMapperGlobalOptions {}
you can remove this line to fix this error:

```
Error: @tsed/common: src/index.ts(10,1): error TS2308: Module "./config/interfaces/PlatformJsonMapperSettings" has already exported a member named 'PlatformJsonMapperSettings'. Consider explicitly re-exporting to resolve the ambiguity.
```

2024-05-27 09:11 UTC, Romakita approved these changes

2024-05-27 09:12 UTC, Romakita approved these changes

2024-05-27 09:12 UTC, Romakita commented
@EinfachHans  Perfect ;)

2024-05-27 09:12 UTC, merged

2024-05-27 09:24 UTC, Romakita commented
:tada: This PR is included in version 7.70.0 :tada:

The release is available on:
- `v7.70.0`
- [GitHub release](https://github.com/tsedio/tsed/releases/tag/v7.70.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: